### ISSUE TITLE
Gitlab environment variables not populating correctly for private instances

### ISSUE THREAD

**Issue by amclin** [semantic-release/gitlab#121]
#115 introduced the ability to automatically retrieve Gitlab to fix #114 

But it doesn't appear to be working correctly. I removed GITLAB_PREFIX and GITLAB_URL so that they could be automatically determined from the Gitlab runner-provided environment variables CI_API_V4_URL

When I look at the error log, I can see that @semantic-release/gitlab reverted to using the **public** gitlab.com and not the private corporate gitlab server that is defined in CI_API_V4_URL,       CI_PROJECT_URL, or CI_PROJECT_PATH.

In my runners, all 3 of those environment variables are defined with the private gitlab server URL, yet the public gitlab.com is what is being used:

```
[10:26:37 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.com/api/v4)
[10:33:11 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/gitlab"
[10:33:11 PM] [semantic-release] › ✖  An error occurred while running semantic-release: GotError [RequestError]: connect ETIMEDOUT 35.231.145.151:443
    at ClientRequest.<anonymous> (/builds/UI-TOOLS/create-usb-nextjs-app/node_modules/@semantic-release/gitlab/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:412:26)
    at ClientRequest.emit (events.js:317:22)
    at ClientRequest.origin.emit (/builds/UI-TOOLS/create-usb-nextjs-app/node_modules/@semantic-release/gitlab/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:423:9)
    at TLSSocket.emit (events.js:305:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'RequestError',
  code: 'ETIMEDOUT',
  host: 'gitlab.com',
  hostname: 'gitlab.com',
  method: 'GET',
  path: '/api/v4/projects/UI-TOOLS%2Fcreate-usb-nextjs-app',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://gitlab.com/api/v4/projects/UI-TOOLS%2Fcreate-usb-nextjs-app',
  gotOptions: {
    path: '/api/v4/projects/UI-TOOLS%2Fcreate-usb-nextjs-app',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'gitlab.com',
    port: null,
    hostname: 'gitlab.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/api/v4/projects/UI-TOOLS%2Fcreate-usb-nextjs-app',
    href: 'https://gitlab.com/api/v4/projects/UI-TOOLS%2Fcreate-usb-nextjs-app',
    retry: {
      retries: [Function (anonymous)],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'private-token': '[secure]',
      accept: 'application/json',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: true,
    cache: false,
    useElectronNet: false,
    method: 'GET',
    forceRefresh: true
  },
  pluginName: '@semantic-release/gitlab'
}
```

I currently provide the repositoryUrl at runtime as a variable so that doesn't need to be explicitly defined in the build scripts: `semantic-release --repository-url=$CI_REPOSITORY_URL`. The only changes I made to take advantage of the new feature is to remove my previously defined GITLAB_PREFIX and GITLAB_URL environment variables and to bump which version of @semantic-release/gitlab I was using.

**Comment by pvdlg** [comment]
What are the values of `GITLAB_CI`, `CI_API_V4_URL`,  `GL_URL`, `GITLAB_URL`, `GL_PREFIX`, `GITLAB_PREFIX`,  `CI_PROJECT_URL` and `CI_PROJECT_PATH` on you CI environmnet?

**Comment by amclin** [comment]
```
GITLAB_CI=true
CI_API_V4_URL=https://<redacted private domain>/api/v4
CI_PROJECT_URL=https://<redacted private domain>/UI-TOOLS/create-usb-nextjs-app
CI_PROJECT_PATH=UI-TOOLS/create-usb-nextjs-app
```

The environment variables `GL_URL`, `GITLAB_URL`, `GL_PREFIX`, GITLAB_PREFIX` are all unset.

**Comment by pvdlg** [comment]
This exact case is tested here: https://github.com/semantic-release/gitlab/blob/e3844298ba0aef30f3dfff53b44fcb4bc2ff8a03/test/resolve-config.test.js#L73

Are you sure those variables are set exactly that way on your CI? Did you printed their values to make sure?
Are you sure your are using the version 4.1.0 of this plugin? Did you make sure it's the version installed in your `node_modules` on the CI? Are you sure you don't have a `yarn.lock` or `package-lock.json` thaat forces an outdated version?

**Comment by amclin** [comment]
I am fairly confident in all of the above, but I will verify tomorrow when I have acesss and can run some tests.

**Comment by amclin** [comment]
> Are you sure those variables are set exactly that way on your CI?

Yes. These variables are set by Gitlab CI itself, not something I control.

> Did you printed their values to make sure?

Yes, I ran `env` during the build to echo out all environment variables:
```
CI_COMMIT_SHORT_SHA=6878b807
CI_RUNNER_EXECUTABLE_ARCH=linux/amd64
CI_COMMIT_TITLE=ci(gitlab): debug env variables
CI_JOB_TOKEN=xxxxxxxxxxxxxxxxxxxx
CI_BUILD_REF_NAME=master
CI_REGISTRY_PASSWORD=xxxxxxxxxxxxxxxxxxxx
CI_RUNNER_TAGS=kubernetes
CI_PIPELINE_URL=https://gitlab.<redacted private domain>/UI-TOOLS/create-usb-nextjs-app/pipelines/65474
YARN_VERSION=1.21.1
CI_JOB_NAME=Install Dependencies
GITLAB_TOKEN=<redacted>
CI_SERVER_VERSION=11.9.8-ee
CI_PAGES_DOMAIN=example.com
GITLAB_CI=true
CI_SERVER_REVISION=c970180
HOSTNAME=runner-zxwrbbry-project-6296-concurrent-0nhm5l
CI_PROJECT_VISIBILITY=internal
OLDPWD=/
CI_DISPOSABLE_ENVIRONMENT=true
CI_COMMIT_SHA=6878b80731fe09b5ec87759b2b2d7accb4a82ac5
CI_COMMIT_MESSAGE=ci(gitlab): debug env variables

FF_USE_LEGACY_VOLUMES_MOUNTING_ORDER=false
CI_BUILD_STAGE=dependencies
CI_PROJECT_URL=https://gitlab.<redacted private domain>/UI-TOOLS/create-usb-nextjs-app
npm_config_registry=https://artifactory.<redacted private domain>/artifactory/api/npm/registry.npmjs.org/
CI_COMMIT_REF_SLUG=master
CI_SERVER_NAME=GitLab
CI_RUNNER_VERSION=12.6.0
CI_BUILD_NAME=Install Dependencies
KUBERNETES_PORT_443_TCP_PROTO=tcp
CI=true
KUBERNETES_PORT_443_TCP_ADDR=<redacted>
CI_REGISTRY_USER=gitlab-ci-token
PIP_INDEX_URL=https://<redacted private domain>/artifactory/api/pypi/pypi-test/simple/
CI_PROJECT_ID=6296
CI_PIPELINE_ID=65474
CI_JOB_URL=https://gitlab.<redacted private domain>/UI-TOOLS/create-usb-nextjs-app/-/jobs/325962
KUBERNETES_PORT=tcp://<redacted>
CI_COMMIT_DESCRIPTION=
PWD=/builds/UI-TOOLS/create-usb-nextjs-app
GITLAB_FEATURES=audit_events,burndown_charts,code_owners,contribution_analytics,elastic_search,export_issues,group_burndown_charts,group_webhooks,issuable_default_templates,issue_board_focus_mode,issue_weights,jenkins_integration,ldap_group_sync,member_lock,merge_request_approvers,multiple_ldap_servers,multiple_issue_assignees,multiple_project_issue_boards,push_rules,project_creation_level,protected_refs_for_users,related_issues,repository_mirrors,repository_size_limit,scoped_issue_board,admin_audit_log,auditor_user,board_assignee_lists,board_milestone_lists,cross_project_pipelines,custom_file_templates,custom_file_templates_for_namespace,email_additional_text,db_load_balancing,deploy_board,extended_audit_events,file_locks,geo,github_project_service_integration,jira_dev_panel_integration,ldap_group_sync_filter,multiple_clusters,multiple_group_issue_boards,multiple_approval_rules,merge_request_performance_metrics,object_storage,group_saml,service_desk,smartcard_auth,unprotection_restrictions,variable_environment_scope,reject_unsigned_commits,commit_committer_check,external_authorization_service,ci_cd_projects,protected_environments,custom_project_templates,packages,code_owner_approval_required,feature_flags,batch_comments,issues_analytics,merge_pipelines
FF_CMD_DISABLE_DELAYED_ERROR_LEVEL_EXPANSION=false
HOME=/root
CI_RUNNER_SHORT_TOKEN=<redacted>
CI_CONCURRENT_ID=0
CI_BUILD_TOKEN=xxxxxxxxxxxxxxxxxxxx
CI_BUILD_ID=325962
GITLAB_USER_NAME=Anthony McLin
CI_COMMIT_BEFORE_SHA=63eb661dda4c37bd8b465ba8d79f7dd1f1fe96f8
CI_PROJECT_PATH_SLUG=ui-tools-create-usb-nextjs-app
KUBERNETES_SERVICE_PORT_HTTPS=443
CI_CONCURRENT_PROJECT_ID=0
CI_API_V4_URL=https://gitlab.<redacted private domain>/api/v4
SSL_CERT_FILE=/etc/ssl/runner-cacerts/cacerts.crt
KUBERNETES_PORT_443_TCP_PORT=443
GITLAB_USER_EMAIL=anthony.mclin@<redacted private domain>
CI_COMMIT_REF_NAME=master
CI_SERVER_VERSION_PATCH=8
CI_PIPELINE_IID=84
GIT_SSL_CAPATH=/etc/ssl/runner-cacerts/cacerts.crt
NODE_VERSION=13.5.0
CI_SERVER_TLS_CA_FILE=/builds/UI-TOOLS/create-usb-nextjs-app.tmp/CI_SERVER_TLS_CA_FILE
CI_RUNNER_ID=184
CI_BUILDS_DIR=/builds
CI_SERVER=yes
KUBERNETES_PORT_443_TCP=tcp://<redacted>
CI_JOB_ID=325962
CI_REPOSITORY_URL=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.<redacted private domain>/UI-TOOLS/create-usb-nextjs-app.git
FF_USE_LEGACY_BUILDS_DIR_FOR_DOCKER=false
GITLAB_USER_LOGIN=<redacted>
CI_RUNNER_REVISION=ac8e767a
CI_CONFIG_PATH=.gitlab-ci.yml
CI_PROJECT_NAME=create-usb-nextjs-app
CI_SERVER_VERSION_MINOR=9
CI_SERVER_VERSION_MAJOR=11
CI_NODE_TOTAL=1
SHLVL=1
CI_RUNNER_DESCRIPTION=kubernetes-gitlab-runner-644696fb6b-vjvrh
cafile=/etc/ssl/runner-cacerts/cacerts.crt
KUBERNETES_SERVICE_PORT=443
CI_PAGES_URL=http://ui-tools.example.com/create-usb-nextjs-app
CI_PROJECT_PATH=UI-TOOLS/create-usb-nextjs-app
GITLAB_USER_ID=2828
CI_BUILD_BEFORE_SHA=63eb661dda4c37bd8b465ba8d79f7dd1f1fe96f8
CI_BUILD_REF=6878b80731fe09b5ec87759b2b2d7accb4a82ac5
PIP_CERT=/etc/ssl/runner-cacerts/cacerts.crt
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CI_PIPELINE_SOURCE=push
CI_PROJECT_NAMESPACE=UI-TOOLS
NODE_EXTRA_CA_CERTS=/etc/ssl/runner-cacerts/cacerts.crt
KUBERNETES_SERVICE_HOST=<redacted>
CI_PROJECT_DIR=/builds/UI-TOOLS/create-usb-nextjs-app
CI_JOB_STAGE=dependencies
CI_BUILD_REF_SLUG=master
_=/usr/bin/env
```

> Are you sure your are using the version 4.1.0 of this plugin?

From `package.json`:
```
"devDependencies": {
    "@semantic-release/gitlab": "^4.1.0",
```
> Did you make sure it's the version installed in your `node_modules` on the CI?

I've since configured the CI to guarantee a clean checkout and workspace. Though since the job runners are spun up from generic Node Docker images, it's going to be a clean checkout and `npm install` on each run.

> Are you sure you don't have a yarn.lock or package-lock.json thaat forces an outdated version?

from `package-lock.json`:
```
 "@semantic-release/gitlab": {
      "version": "4.1.0",
```

**Comment by pvdlg** [comment]
Are you using semantic-release version 15.14.0? With a lower version it wouldn't work.

**Comment by amclin** [comment]
I run semantic-release with `npx semantic-release` and not a local devDependency, so it should always be the latest

**Comment by amclin** [comment]
My full command to run semantic-release is:
`npx semantic-release "--repository-url=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.<redacted private domain>/UI-TOOLS/create-usb-nextjs-app.git"`

**Comment by amclin** [comment]
I've verified that the latest version of `semantic-release` in our private registry mirror is 15.14.0, so I can be confident that 15.14.0 is what is being run by `npx semantic-release` on the CI environment. Though if there's a way I can explicitly verify this, I'm open to suggestions.

**Comment by pvdlg** [comment]
The first line of log indicate the version.

**Comment by amclin** [comment]
Ok, I can confirm that for some reason running `npx semantic-release` on my CI environment is loading v15.13.1 instead of the latest v15.14.0 (though this doesn't make a lot of sense since it's not globally in the Docker image).

I can successfully force v15.14 by using the command `npx --package semantic-release@^15.14.0 semantic-release` instead

@pvdlg thank you for your assistance in helping me get this resolved
