### ISSUE TITLE
Support on "remote: You are not allowed to upload code."

### ISSUE THREAD

**Issue by linceaerian** [semantic-release/gitlab#137]
Hello Maintainers,

I'm failing to have the semantic-release for Gitlab to work correctly.
My pipeline "execute" correctly as long as you do not use debug...

![image](https://user-images.githubusercontent.com/1318470/76170491-aaf44780-6182-11ea-8ed5-430dfb98334d.png)

Except that it do nothing.... so looking at:
https://gitlab.com/gitlab-org/gitlab-eslint-config/-/jobs/130898644

I'm expecting it's quitting in the "middle", I first got no lead until I used debug, where you have the following output:

```
(...)
$ npm install @semantic-release/gitlab
00:36
npm WARN saveError ENOENT: no such file or directory, open '/builds/geolocation.fr/app_engine/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/builds/geolocation.fr/app_engine/package.json'
npm WARN @semantic-release/gitlab@6.0.2 requires a peer of semantic-release@>=15.8.0 <18.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN app_engine No description
npm WARN app_engine No repository field.
npm WARN app_engine No README data
npm WARN app_engine No license field.
+ @semantic-release/gitlab@6.0.2
added 79 packages from 101 contributors and audited 104 packages in 5.858s
6 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
$ npx semantic-release --debug
npx: installed 761 in 23.193s
[7:43:42 PM] [semantic-release] › ℹ  Running semantic-release version 17.0.4
2020-03-08T19:43:42.219Z semantic-release:config load config from: /builds/geolocation.fr/app_engine/.releaserc.yml
2020-03-08T19:43:42.230Z semantic-release:config options values: {
  branches: [
    'master',
    '+([0-9])?(.{+([0-9]),x}).x',
    { name: 'dev', prerelease: 'dev' }
  ],
  repositoryUrl: 'https://gitlab-ci-token:[secure]@gitlab.com/geolocation.fr/app_engine.git',
  tagFormat: 'v${version}',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/gitlab'
  ],
  publish: [ '@semantic-release/gitlab' ],
  verifyConditions: [ '@semantic-release/gitlab' ],
  _: [],
  debug: true,
  '$0': '/root/.npm/_npx/21/bin/semantic-release'
}
2020-03-08T19:43:42.446Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: {}
[7:43:42 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
2020-03-08T19:43:42.448Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[7:43:42 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2020-03-08T19:43:42.449Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[7:43:42 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2020-03-08T19:43:42.450Z semantic-release:plugins options for @semantic-release/gitlab/publish: {}
[7:43:42 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
2020-03-08T19:43:42.674Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://gitlab-ci-token:[secure]@gitlab.com/geolocation.fr/app_engine.git HEAD:dev
remote: You are not allowed to upload code.
fatal: unable to access 'https://gitlab-ci-token:[secure]@gitlab.com/geolocation.fr/app_engine.git/': The requested URL returned error: 403
    at makeError (/root/.npm/_npx/21/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/root/.npm/_npx/21/lib/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async verifyAuth (/root/.npm/_npx/21/lib/node_modules/semantic-release/lib/git.js:207:5)
    at async module.exports (/root/.npm/_npx/21/lib/node_modules/semantic-release/lib/get-git-auth-url.js:43:5)
    at async run (/root/.npm/_npx/21/lib/node_modules/semantic-release/index.js:55:27)
    at async module.exports (/root/.npm/_npx/21/lib/node_modules/semantic-release/index.js:259:22)
    at async module.exports (/root/.npm/_npx/21/lib/node_modules/semantic-release/cli.js:55:5)
2020-03-08T19:43:45.362Z semantic-release:get-tags found tags for branch master: [ { gitTag: 'v1.0.0', version: '1.0.0', channels: [ null ] } ]
2020-03-08T19:43:45.375Z semantic-release:get-tags found tags for branch dev: [ { gitTag: 'v1.0.0', version: '1.0.0', channels: [ null ] } ]
[7:43:45 PM] [semantic-release] › ✔  Run automated release from branch dev on repository https://gitlab-ci-token:[secure]@gitlab.com/geolocation.fr/app_engine.git
[7:43:45 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[7:43:45 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
2020-03-08T19:43:45.589Z semantic-release:gitlab apiUrl: 'https://gitlab.com/api/v4'
2020-03-08T19:43:45.590Z semantic-release:gitlab repoId: 'geolocation.fr/app_engine'
[7:43:45 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.com/api/v4)
Job succeeded
```

So you can see a beautiful:

```
2020-03-08T19:43:42.674Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://gitlab-ci-token:[secure]@gitlab.com/geolocation.fr/app_engine.git HEAD:dev
remote: You are not allowed to upload code.
fatal: unable to access 'https://gitlab-ci-token:[secure]@gitlab.com/geolocation.fr/app_engine.git/': The requested URL returned error: 403
```

Except that... the token as correct rights as seen in:

![image](https://user-images.githubusercontent.com/1318470/76170336-51d7e400-6181-11ea-86ee-d2f61c8d8073.png)

And that executing the command manually work correctly...

![image](https://user-images.githubusercontent.com/1318470/76170363-8cda1780-6181-11ea-8000-9731bd2ea92a.png)

I've set my variables as:

![image](https://user-images.githubusercontent.com/1318470/76170371-9a8f9d00-6181-11ea-97b9-ef06bd9e7c2d.png)

As per the documentation I think...
I've followed the example described here:
https://levelup.gitconnected.com/semantic-versioning-and-release-automation-on-gitlab-9ba16af0c21

So with .releaserc.yml as:

``` 
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/gitlab"
branches:
  - "master"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "dev"
    prerelease: "dev"
```

And .release-ci.yml (Which is then included as stage in .gitlab-ci.yml)

``` 
release:
  image: node:13
  stage: release
  only:
    refs:
    - master
    - dev
    # This matches maintenance branches
    - /^(([0-9]+)\.)?([0-9]+)\.x/
    # This matches pre-releases
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/ 
  script:
    - npm install @semantic-release/gitlab
    - npx semantic-release --debug
```

The branchs are protected as:

![image](https://user-images.githubusercontent.com/1318470/76170396-dfb3cf00-6181-11ea-9878-75b5c65ce568.png)

Would you have any idea that could help find it why the push is failing ? :)

Thanks !

**Comment by ext** [comment]
I've just run into this myself, it was working fine 6 days ago with no configuration changes since then. Maybe something changed in gitlab?

**Comment by jacklei** [comment]
I'm debuging the same problem at the moment and I have a hunch on what it is.

lib/verify.js has this 
```
.get(urlJoin(gitlabApiUrl, `/projects/${encodeURIComponent(repoId)}`), {
```
where repoId is the `namespace/project`, however gitlab api needs the `/` to be url encoded. [gitlab api doc](https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding)


Quick test on my instance of gitlab.
```
>  curl -sL --header "PRIVATE-TOKEN: $TOKEN" $GITLAB_URL/api/v4/projects/jack/gitlabtest | jq .
{
  "error": "404 Not Found"
}
```

```
> curl -sL --header "PRIVATE-TOKEN: $TOKEN" $GITLAB_URL/api/v4/projects/jack%2Fgitlabtest | jq .
{
  "id": 1947,
  "description": "",
...
```

**Comment by jacklei** [comment]
I am having this issue on my on-prem gitlab instance (12.8.1-ee) but not gitlab.com with the same code.

@linceaerian, I noticed that in your screenshot your `GITLAB_TOKEN` has protected enabled. From your error message, you are on the `dev` branch. Is the `dev` branch protected? If not, the `GITLAB_TOKEN` would not be set.

**Comment by linceaerian** [comment]
@jacklei  Yes, it's protected like shown in the last screenshot. I've blocked due to this on another CI so I did not forget it :)

I've already tried "unprotected", "unmasked", change to use "GL_TOKEN", try to set up an intermediary "variable" in the CI.... but to no avail :P

On another infos, I've got the same thing than you in the curl on Gitlab.com

```bash
export TOKEN=""; curl -sL --header "PRIVATE-TOKEN: $TOKEN" https://gitlab.com/api/v4/projects/geolocation.fr/app_engine/ 
{"error":"404 Not Found"}%  
export TOKEN=""; curl -sL --header "PRIVATE-TOKEN: $TOKEN" https://gitlab.com/api/v4/projects/geolocation.fr%2Fapp_engine/
{"id":17266875,"description":"","name":"app_engine","name_with_namespace":"geolocation.fr / app_engine","path":"app_engine","path_with_namespace":"geolocation.fr/app_engine","created_at":"2020-03-03T19:46:26.742Z","default_branch":"master", XXXXX}
```

However it should not be impacting as it was a "git" command displayed in the debug (So I expect it's git that's doing the encoding) and the command itself was working fine.

**Comment by ext** [comment]
I get a similar message but not the same:

```
2020-03-08T21:51:29.878Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://gitlab.com/html-validate/html-validate.git HEAD:master
 remote: HTTP Basic: Access denied
 fatal: Authentication failed for 'https://gitlab.com/html-validate/html-validate.git/'
     at makeError (/builds/html-validate/html-validate/node_modules/semantic-release/node_modules/execa/lib/error.js:58:11)
     at handlePromise (/builds/html-validate/html-validate/node_modules/semantic-release/node_modules/execa/index.js:114:26)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
     at async verifyAuth (/builds/html-validate/html-validate/node_modules/semantic-release/lib/git.js:207:5)
     at async module.exports (/builds/html-validate/html-validate/node_modules/semantic-release/lib/get-git-auth-url.js:43:5)
     at async run (/builds/html-validate/html-validate/node_modules/semantic-release/index.js:55:27)
     at async module.exports (/builds/html-validate/html-validate/node_modules/semantic-release/index.js:259:22)
     at async module.exports (/builds/html-validate/html-validate/node_modules/semantic-release/cli.js:55:5)
```

This is only visible when using `--debug` otherwise the pipeline succeeds without doing anything. I'm not sure how to fix this even temporary.

`GL_TOKEN` is set (and is protected and masked), it runs on `master` branch which is protected. Worked fine a week ago.

**Comment by pvdlg** [comment]
You have that in the debug logs because semantic-release tries a `push --dry-run` fist without modifying the repo URL. If it fails it adds `gitlab-ci-token:<GL_TOKEN>` to the URL.

The command `git push --dry-run --no-verify https://gitlab-ci-token:<GL_TOKEN>@gitlab.com/<repo-id>.git HEAD:<branch>` has to be allowed GitLab. It seems for some reasons GitLAb ignore your token settings and disallow this command.

btw, that's done by semantic-release core not by the GitLab plugin.
