### ISSUE TITLE
Cannot read property "statusCode" of undefined

### ISSUE THREAD

**Issue by hahnartefakt** [semantic-release/gitlab#221]
Hello everyone,

i tried to install semantic release with the gitlab pluging but everytime i try to run my container it fails at the "verifyConditions" stage. I already added the GITLAB_TOKEN (Gitlab environment variable), HTTP_PROXY (Gitlab EV), the package.json as well as a stage for my CI/CD Pipeline. I just found one issue where no answer was given. I think at the end it has something to do with the many regulations of my company environment but maybe you can help me.

I work with the gitlab runner, which starts a docker container with all dependencies. If I manipulate the Gitlab project manually with the "git" command it works. Which means the GITLAB_TOKEN works properly.

Pipeline Job:

```
[10:58:01 AM] [semantic-release] › ℹ  Running semantic-release version 15.14.0
2021-02-05T10:58:01.780Z semantic-release:config load config from: /builds/gitlab/andre.kohls/test-automation-template/package.json
2021-02-05T10:58:01.820Z semantic-release:config options values: {
  branch: 'master',
  repositoryUrl: 'https://gitlab-ci-token:[secure]@[company_workbench_url].de/gitlab/andre.kohls/test-automation-template.git',
  tagFormat: 'v${version}',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/gitlab'
  ],
  branches: [ 'master', 'versioning', 'next' ],
  _: [],
  debug: true,
  '$0': 'node_modules/.bin/semantic-release'
}
2021-02-05T10:58:02.026Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: {}
[10:58:02 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
2021-02-05T10:58:02.028Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
2021-02-05T10:58:02.028Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[10:58:02 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[10:58:02 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[10:58:02 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
2021-02-05T10:58:02.028Z semantic-release:plugins options for @semantic-release/gitlab/publish: {}
[10:58:02 AM] [semantic-release] › ✔  Run automated release from branch master
2021-02-05T10:58:02.422Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run https://gitlab-ci-token:[secure]@[company_workbench_url]/gitlab/andre.kohls/test-automation-template.git HEAD:master
    at makeError (/builds/gitlab/andre.kohls/test-automation-template/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/builds/gitlab/andre.kohls/test-automation-template/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async verifyAuth (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/git.js:123:5)
    at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/get-git-auth-url.js:43:5)
    at async run (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/index.js:62:27)
    at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/index.js:176:22)
    at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/cli.js:55:5)
[10:58:02 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[10:58:02 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
2021-02-05T10:58:02.773Z semantic-release:gitlab apiUrl: 'https://[company_workbench_url]/gitlab/api/v4'
2021-02-05T10:58:02.773Z semantic-release:gitlab repoId: 'andre.kohls/test-automation-template'
[10:58:02 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://[company_workbench_url]/gitlab/api/v4)
[10:58:02 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/gitlab"
[10:58:02 AM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Cannot read property 'statusCode' of undefined
    at module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/@semantic-release/gitlab/lib/verify.js:62:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  pluginName: '@semantic-release/gitlab'
}
AggregateError: 
    TypeError: Cannot read property 'statusCode' of undefined
        at module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/@semantic-release/gitlab/lib/verify.js:62:26)
    at /builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/index.js:84:3)
    at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/index.js:176:22)
    at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/cli.js:55:5)
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

package.json:
```
{
    "name": "semantic-release-config",
    "release": {
        "branches": ["master", "next"],
        "plugins": [
            "@semantic-release/commit-analyzer",
            "@semantic-release/release-notes-generator",
            "@semantic-release/gitlab"
        ]
    }
}
```

gitlab-ci.yml:
```
release:
  image: node:13
  stage: release
  tags:
    - run_docker
  before_script:
    - npm install semantic-release@15.14.0 @semantic-release/gitlab@6.0.8

  script:
    - npx semantic-release --debug
```

I already tried to run semantic-release with the latest version, as well as for each plugin.

I hope you can help me and thanks in advance.

**Comment by travi** [comment]
are you certain that you have the most recent version of the gitlab plugin? there was [a fix](https://github.com/semantic-release/gitlab/pull/214) released in v6.0.9 that would improve reporting of the actual error instead of getting stuck on an error like the one you report. if you haven't upgraded that plugin, please try that and see if it at least provides you with a more helpful error.

**Comment by hahnartefakt** [comment]
Thanks for the fast answer!

I changed the version of gitlab to 6.0.9 and got the following output. 

```
$ npm install semantic-release@15.14.0 @semantic-release/gitlab@6.0.9
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @octokit/plugin-request-log@1.0.3 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.
npm WARN semantic-release-config@ No repository field.
npm WARN semantic-release-config@ No license field.
+ semantic-release@15.14.0
+ @semantic-release/gitlab@6.0.9
added 807 packages from 1065 contributors and audited 807 packages in 65.43s
30 packages are looking for funding
  run `npm fund` for details
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
$ npx semantic-release --debug
[8:17:33 AM] [semantic-release] › ℹ  Running semantic-release version 15.14.0
2021-02-10T08:17:33.094Z semantic-release:config load config from: /builds/gitlab/andre.kohls/test-automation-template/package.json
2021-02-10T08:17:33.133Z semantic-release:config options values: {
  branch: 'master',
  repositoryUrl: 'https://gitlab-ci-token:[secure]@wom-wbench.workbench.telekom.de/gitlab/andre.kohls/test-automation-template.git',
  tagFormat: 'v${version}',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/gitlab'
  ],
  branches: [ 'master', 'next' ],
  _: [],
  debug: true,
  '$0': 'node_modules/.bin/semantic-release'
}
2021-02-10T08:17:33.334Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: {}
[8:17:33 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
2021-02-10T08:17:33.336Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
2021-02-10T08:17:33.336Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
2021-02-10T08:17:33.337Z semantic-release:plugins options for @semantic-release/gitlab/publish: {}
[8:17:33 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[8:17:33 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[8:17:33 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[8:17:33 AM] [semantic-release] › ✔  Run automated release from branch master
2021-02-10T08:17:33.711Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run https://gitlab-ci-token:[secure]@wom-wbench.workbench.telekom.de/gitlab/andre.kohls/test-automation-template.git HEAD:master
    at makeError (/builds/gitlab/andre.kohls/test-automation-template/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/builds/gitlab/andre.kohls/test-automation-template/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async verifyAuth (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/git.js:123:5)
    at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/get-git-auth-url.js:43:5)
    at async run (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/index.js:62:27)
    at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/index.js:176:22)
    at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/cli.js:55:5)
[8:17:34 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[8:17:34 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
2021-02-10T08:17:34.045Z semantic-release:gitlab apiUrl: 'https://wom-wbench.workbench.telekom.de/gitlab/api/v4'
2021-02-10T08:17:34.045Z semantic-release:gitlab repoId: 'andre.kohls/test-automation-template'
[8:17:34 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://wom-wbench.workbench.telekom.de/gitlab/api/v4)
[8:17:34 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/gitlab"
[8:17:34 AM] [semantic-release] › ✖  An error occurred while running semantic-release: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseBody (/builds/gitlab/andre.kohls/test-automation-template/node_modules/got/dist/source/as-promise.js:12:46)
    at /builds/gitlab/andre.kohls/test-automation-template/node_modules/got/dist/source/as-promise.js:138:47
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/@semantic-release/gitlab/lib/verify.js:52:11)
    at async verifyConditions (/builds/gitlab/andre.kohls/test-automation-template/node_modules/@semantic-release/gitlab/index.js:9:3)
    at async validator (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as verifyConditions] (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/index.js:80:11) {
  pluginName: '@semantic-release/gitlab'
}
AggregateError: 
    SyntaxError: Unexpected token < in JSON at position 0
        at JSON.parse (<anonymous>)
        at parseBody (/builds/gitlab/andre.kohls/test-automation-template/node_modules/got/dist/source/as-promise.js:12:46)
        at /builds/gitlab/andre.kohls/test-automation-template/node_modules/got/dist/source/as-promise.js:138:47
        at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/@semantic-release/gitlab/lib/verify.js:52:11)
        at async verifyConditions (/builds/gitlab/andre.kohls/test-automation-template/node_modules/@semantic-release/gitlab/index.js:9:3)
        at async validator (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
        at async /builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
        at async /builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
        at async Object.pluginsConf.<computed> [as verifyConditions] (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at /builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/index.js:84:3)
    at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/index.js:176:22)
    at async module.exports (/builds/gitlab/andre.kohls/test-automation-template/node_modules/semantic-release/cli.js:55:5)
ERROR: Job failed: exit code 1
```
I remember that I already had this error and found no solution to this problem.

**Comment by nfriend** [comment]
> An error occurred while running semantic-release: SyntaxError: Unexpected token < in JSON at position 0

@hahnartefakt Interesting, this makes me think that when the plugin sends a request to GitLab's REST API, it's getting back XML instead of JSON like it expects.

I see that the URL to your GitLab instance is `https://[company_workbench_url]/gitlab/api/v4`. I'm not sure if this is the literal address it's using, or if `[company_workbench_url]` is being substituted before the request is made 🤔. Either way, if this URL is incorrect, then maybe the response is returning an HTML 404 page. (Which the plugin then tries to parse as JSON.)

Can you verify that the URL to your GitLab instance is correctly set up?

**Comment by hahnartefakt** [comment]
> Can you verify that the URL to your GitLab instance is correctly set up?

I just substituted the original URL of my company, just for this post. It uses the correct URL to the GitLab instance. The correct URL which is parsed via the environment variables is something like:
`https://something.something.de/gitlab/api/v4`
Maybe it has something to do with the way our GitLab works. It is integrated in a "workbench" where many of our services are placed at. Because of compliance and security we have many restrictions and problems with using specific tools. Is possible that there have to be made some changes to the GitLab configuration?

**Comment by nfriend** [comment]
> I just substituted the original URL of my company, just for this post. It uses the correct URL to the GitLab instance.

@hahnartefakt Cool, thanks for confirming.

One thing you could try is manually submitting a GET request (e.g. with `curl`) to `https://something.something.de/gitlab/api/v4/projects/<repoID>` with the `PRIVATE-TOKEN: <your token here>` header. This is what `@semantic-release/gitlab` is doing [behind the scenes](https://github.com/semantic-release/gitlab/blob/c1e237ec8afb0e49072ffd6b9c8e9e29f4979cab/lib/verify.js#L53). If this fails, it might give you a better idea of what's going wrong.

**Comment by hahnartefakt** [comment]
Okay I did the request.

```
curl -H 'PRIVATE-TOKEN: [MASKED]' https://something.de/gitlab/api/v4/projects/254 -v
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.52.41.49...
* TCP_NODELAY set
* Connected to something.de (10.52.41.49) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [108 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4786 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [589 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=DE; O=Something; OU=Resource & Project Mgmt. Applications; ST=Nordrhein-Westfalen; L=Bonn; CN=*.something.de
*  start date: Apr 17 10:21:40 2020 GMT
*  expire date: Apr 22 23:59:59 2021 GMT
*  subjectAltName: host "something.de" matched cert's "*.something.de"
*  issuer: C=DE; O=T-Systems International GmbH; OU=T-Systems Trust Center; ST=Nordrhein Westfalen; postalCode=57250; L=Netphen; street=Untere Industriestr. 20; CN=TeleSec ServerPass Class 2 CA
*  SSL certificate verify ok.
} [5 bytes data]
> GET /gitlab/api/v4/projects/254 HTTP/1.1
> Host: something.de
> User-Agent: curl/7.52.1
> Accept: */*
> PRIVATE-TOKEN: [MASKED]
> 
{ [5 bytes data]
< HTTP/1.1 302 
< Date: Thu, 11 Feb 2021 08:49:31 GMT
< Server: portal
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< X-Frame-Options: SAMEORIGIN
< Content-Length: 0
< Set-Cookie: JSESSIONID=60DCF677D58B35EA05FB2A53073BBC15; Max-Age=86400; Expires=Fri, 12-Feb-2021 08:49:31 GMT; Path=/; Secure; HttpOnly
< Location: https://workbench.something.de/deeplinklogin
< Connection: close
< 
* Curl_http_done: called premature == 0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
} [5 bytes data]
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
```

It seems like I get redirected to our Workbench's" login page `Location: https://workbench.something.de/deeplinklogin`. Is that correct? Maybe that is what happens when I use the `@semantic-release/gitlab` plugin. As I can see there is no exception for the status code 302 in the `verify.js`.

**Comment by nfriend** [comment]
> It seems like I get redirected to our Workbench's" login page Location: https://workbench.something.de/deeplinklogin

@hahnartefakt Ah, that looks like the root cause to me! The plugin won't know how to make an API request through the extra layer of authentication imposed by your network.

Unfortunately, I'm not sure the best way to go about solving this 🤔. Perhaps your network admins might have some ideas on how to allow these requests to go through? Sorry I can't be of more help!

**Comment by hahnartefakt** [comment]
Thought so :/ But I appreciate the help. I already contacted the network admins because :)

Thank you for your help until this point ;)
