### ISSUE TITLE
Error 409

### ISSUE THREAD

**Issue by EvanCarroll** [semantic-release/gitlab#256]
I'm still getting this Error 409. It would be great if nothing else to have more information than `--debug` provides,

```
[4:36:12 PM] [semantic-release] [@semantic-release/gitlab] › ✖  An error occurred while making a request to the GitLab release API:
HTTPError: Response code 409 (Conflict)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@semantic-release/gitlab/node_modules/got/dist/source/as-promise.js:118:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[4:36:12 PM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/gitlab"
[4:36:12 PM] [semantic-release] › ✖  An error occurred while running semantic-release: HTTPError: Response code 409 (Conflict)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@semantic-release/gitlab/node_modules/got/dist/source/as-promise.js:118:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  pluginName: '@semantic-release/gitlab'
}
HTTPError: Response code 409 (Conflict)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@semantic-release/gitlab/node_modules/got/dist/source/as-promise.js:118:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  pluginName: '@semantic-release/gitlab'
}
```

This works locally when I run, 

    CI=1 GITLAB_TOKEN=token npx semantic-release --publish --ci

So I'm at a loss for why it wouldn't work on the smoker.

**Comment by EvanCarroll** [comment]
I have hacked my source to provide a `name`, which was suggested here https://github.com/semantic-release/gitlab/issues/66

I've confirmed this does **NOT** work for me.

See the log here: [log.txt](https://github.com/semantic-release/gitlab/files/6864285/log.txt)

**Comment by kphunter** [comment]
In my case, the GitLab tags had been removed but the `Releases` still contained refs that conflicted. Removing these allowed `semantic-release` to run error-free.

**Comment by ericschmar** [comment]
> In my case, the GitLab tags had been removed but the `Releases` still contained refs that conflicted. Removing these allowed `semantic-release` to run error-free.

Can you elaborate on what you had to do here? I'm not sure I understand. I are you saying you edited individual releases in GitLab to remove the refs in parenthesis that were pointing to commits?

**Comment by EvanCarroll** [comment]
@ericschmar I believe what @kphunter is saying is he had to use the GitLab Releases API to delete the corresponding releases. But tagging him will help get an answer to that. ;)

**Comment by kphunter** [comment]
> @ericschmar I believe what @kphunter is saying is he had to use the GitLab Releases API to delete the corresponding releases. But tagging him will help get an answer to that. ;)

That's correct - either remove the [GitLab Release](https://docs.gitlab.com/ee/user/project/releases/) via [the API](https://docs.gitlab.com/ee/api/releases/#delete-a-release) or manually through the UI to get rid of the reference that is causing the conflict.
