### ISSUE TITLE
Fail on git push --dry-run --no-verify: remote: HTTP Basic: Access denied

### ISSUE THREAD

**Issue by EvanCarroll** [semantic-release/gitlab#259]
I've tried authenticating with 

* Project Access token 
  * w/ just API
  * w/ API & Write Repo
* Personal Access token with API & Write Repo

I still get failures like this,

```
[8:13:17 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
2021-07-22T20:13:17.637Z semantic-release:get-git-auth-url Verifying ssh auth by attempting to push to  https://gitlab.awe.eco.cpanel.net/foo/bar.git
2021-07-22T20:13:18.220Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://gitlab.awe.eco.cpanel.net/foo/bar.git HEAD:main
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.awe.eco.cpanel.net/foo/bar.git/'
    at makeError (/usr/local/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/semantic-release/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async verifyAuth (/usr/local/lib/node_modules/semantic-release/lib/git.js:207:5)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/lib/get-git-auth-url.js:91:5)
    at async run (/usr/local/lib/node_modules/semantic-release/index.js:56:27)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/cli.js:55:5)
2021-07-22T20:13:18.220Z semantic-release:get-git-auth-url SSH key auth failed, falling back to https.
2021-07-22T20:13:19.134Z semantic-release:get-tags found tags for branch main: [ { gitTag: 'v1.0.0', version: '1.0.0', channels: [ null ] } ]
```

However, with each one of these three tokens I can confirm it works with

```sh
git push --dry-run --no-verify https://oauth:GITLAB_TOKEN@gitlab.awe.eco.cpanel.net/foo/bar.git
```

I guess the questions here are why is `semantic-release:git`'s `verifyAuth` being called, and why doesn't it use the `GITLAB_TOKEN` that I provide?

**Comment by EvanCarroll** [comment]
Well, that was a waste of 8 hours.

My problem was my token was in quotes. Something I would have **IMMEDIATELY** figured out if either,

1. something warned me that the token was in quotes,
2. the token was unconfigurably changed to `[secure]` everywhere it was outputted..

**Comment by EvanCarroll** [comment]
If anyone else does the same thing, I would love to see you comment on here and fess up to it. I do wonder how common this is.

**Comment by mohit497** [comment]
found the same  issue today trying to setup CI on github actions

**Comment by david-shepard** [comment]
I'm having a similar issue, I have `GH_TOKEN` set and it insists on trying SSH authentication. I cannot figure out why.
