### ISSUE TITLE
Not Found on gitlab 14.1.0

### ISSUE THREAD

**Issue by c3098051** [semantic-release/gitlab#263]
I updated gitlab to community 14.1.0 lately, and running semantic-release failed.
semantic-release/gitlab could uploads the file like version.txt, and changelog, but after that, the job is failed due to "Not Found" error. 

[8:53:39 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Uploaded file: /uploads/24c08e17680d23f5b07aef90ff1d33ee/VERSION.txt
[8:53:39 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Uploaded file: /uploads/2456b13085aefd6b871c71a3f76d52b2/CHANGELOG.md
2021-07-26T12:53:39.355Z 
semantic-release:gitlab Update git tag '1.1.2-develop.36' with commit '611ca8bf3e311bed3d97121a9622d22379c01a56' and release description

[8:53:39 PM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/gitlab"
[8:53:39 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { HTTPError: Response code 404 (Not Found)
    at EventEmitter.emitter.on (/usr/local/share/.config/yarn/global/node_modules/got/dist/source/as-promise.js:118:31)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'HTTPError', pluginName: '@semantic-release/gitlab' }
{ HTTPError: Response code 404 (Not Found)
    at EventEmitter.emitter.on (/usr/local/share/.config/yarn/global/node_modules/got/dist/source/as-promise.js:118:31)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'HTTPError', pluginName: '@semantic-release/gitlab' }

**Comment by makampf** [comment]
> It was due to the old version library. I was using 6.0.4, upgrading to 6.2.1 resolved the issue. (self close)

Which library?
