### ISSUE TITLE
Gitlab releases endpoint change

### ISSUE THREAD

**Issue by r4j4h** [semantic-release/gitlab#266]
We recently upgraded to Gitlab 14.0 and it would appear that Gitlab failed to document some breaking changes to the Release/Tags API, at least that I could find after some extensive looking.

If my hunch is correct, this breaks semantic-release/gitlab because of https://github.com/semantic-release/gitlab/blob/master/lib/publish.js#L86 where it always tries to use `/tags/release` to create releases, which apparently no longer works.

According to some old copy of Gitlab docs, http://www.obsis.unb.br/gitlab/help/api/tags.md#create-a-new-release that path did work.

However, in the official docs any such mention of that ability has been wholesale removed:
https://docs.gitlab.com/ee/api/tags.html
and releases has a "Add a tag" first-class now
https://docs.gitlab.com/ee/api/releases/#create-a-release

Even more frustrating, it isn't clear in the docs when this was removed, at least I couldn't find it in any of the "Version history" tables on those pages, nor in the following places or their history tabs:
- https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/doc/api/tags.md
- https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/doc/api/protected_tags.md
- https://gitlab.com/gitlab-org/gitlab-foss/-/tree/master/doc/api/releases

But, I did find this commit (2 years old) from gitlab search, confirming this is true and tag endpoint is deprecated: https://gitlab.com/gitlab-org/gitlab-foss/-/commit/1ea2d9faa518f6b769b05a71a1f93b4ea0226bc1

So I think semantic-release/gitlab needs to first query gitlab version, and then use the appropriate call, otherwise it will continue to create Git tags and fail to create releases against new Gitlab's with errors like this:

```
[5:45:40 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
[5:45:40 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:45:40 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:45:40 PM] [semantic-release] › ✔  Created tag v1.148.8
[5:45:40 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/gitlab"
[5:45:40 PM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/gitlab"
[5:45:40 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { HTTPError: Response code 404 (Not Found)
    at EventEmitter.emitter.on (/builds/project/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  host: 'gitlab.instance.com',
  hostname: 'gitlab.instance.com',
  method: 'POST',
  path:
   '/api/v4/projects/project/repository/tags/v1.148.8/release',
  socketPath: undefined,
  ...
```

It would appear that things worked in 13.x and so I think Gitlab 14.0 is where it got deprecated, but I have not verified that. 

The commit I found that first mentioned this endpoint's deprecation was for 11.7. So I imagine the plugin could also safely use the new API on Gitlabs probably v12 and up.

**Comment by r4j4h** [comment]
Closing this as it ends up we are simply using an out of date version of this plugin 🤦‍♀️
