### ISSUE TITLE
Semantic Release suddenly stopped working

### ISSUE THREAD

**Issue by cpflugra** [semantic-release/gitlab#292]
Semantic Release suddenly stopped working for us. I'm not sure about the exact cause but I'll try to give you all relevant details.

We use a self-hosted GitLab instance. After upgrading to GitLab Community Edition 14.3.3 we noticed Semantic Release not working anymore. I'm not sure which GitLab CE version we used before but it must have been 14.2.x or 14.3.x. If it's important I can try to find it out.

We use a docker image with Semantic Release version 17.4.2 in our CI/CD. I also tried upgrading to the latest 18.x.x version but the problem was the same.

We use the following command to run Semantic Release: `npx semantic-release -t \${version} --debug`

In its log output Semantic Release states that the repository does not exist. I've had a look at the source code of the semantic-release/gitlab plugin and noticed something strange:

The `repoId` variable is equivalent to the repo's namespace and name, not the numeric value. Let's say the effected repo has numeric Id 1234, is named "foo" and is part of a group "bar" then the repoId is not 1234 but rather "bar/foo".

The part I don't understand is that the part that fails calls the [projects api](https://docs.gitlab.com/ee/api/projects.html) of GitLab api/v4 using this repoId. However the projects API requires the numeric id to retrieve info about a project. 

I've tried to reproduce what semantic-release/gitlab does using curl. When I query `/api/v4/projects/1234` and pass the 'PRIVATE-TOKEN' in the header, I retrieve the repo details as expected. When I change the `1234` part of the url to `bar/foo` I get a HTTP 404 as a response. The second variant is what semantic-release/gitlab is doing in our pipeline and the reason it fails.

In the source code I can see that the `repoId` variable is equivalent to the [predefined GitLab CI variable](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html) `CI_PROJECT_PATH`.

What I cannot explain is how this ever worked in the past. Either the projects API has changed or the content of the CI_PROJECT_PATH. Neither of these seem likely to me so maybe I've overlooked something.

The fix for us is easy though, but it's a very dirty workaround. Before invoking Semantic Release we now overwrite the content of `CI_PROJECT_PATH` with the content of `CI_PROJECT_ID`, so Semantic Release calls the projects API with the numeric id: `CI_PROJECT_PATH=$CI_PROJECT_ID`
This only works because the non numeric value isn't used anywhere else, though. 

Let me know what you think of this and if we can expect an official fix for it.

Below is the output of the GitLab CI job after calling Semantic Release. Some potentially confidential content is replaced by 'xxx':
```
[1:13:42 PM] [semantic-release] › ℹ  Running semantic-release version 17.4.2
2021-10-26T13:13:42.509Z semantic-release:config load config from: /builds/[secure]/0/xxx/xxx/xxx/.releaserc.yml
2021-10-26T13:13:42.545Z semantic-release:config options values: {
  branches: [ 'master' ],
  repositoryUrl: 'https://gitlab-ci-token:[secure]@xxx.xxx.xxx/xxx/xxx/xxx.git',
  tagFormat: '${version}',
  plugins: [
    [ '@semantic-release/commit-analyzer', [Object] ],
    '@semantic-release/release-notes-generator',
    [ '@semantic-release/gitlab', [Object] ]
  ],
  _: [],
  t: '${version}',
  'tag-format': '${version}',
  debug: true,
  '$0': '/usr/local/bin/semantic-release'
}
2021-10-26T13:13:42.768Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: { gitlabUrl: 'https://xxx.xxx.xxx' }
[1:13:42 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
2021-10-26T13:13:42.770Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {
  preset: 'angular',
  releaseRules: [
    { type: 'major', release: 'major' },
    { type: 'feat', release: 'minor' },
    { type: 'fix', release: 'patch' }
  ]
}
[1:13:42 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2021-10-26T13:13:42.770Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[1:13:42 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2021-10-26T13:13:42.770Z semantic-release:plugins options for @semantic-release/gitlab/publish: { gitlabUrl: 'https://xxx.xxx.xxx' }
[1:13:42 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
2021-10-26T13:13:42.789Z semantic-release:get-git-auth-url Verifying ssh auth by attempting to push to  https://gitlab-ci-token:[secure]@xxx.xxx.xxx/xxx/xxx/xxx.git
2021-10-26T13:13:42.922Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://gitlab-ci-token:[secure]@xxx.xxx.xxx/xxx/xxx/xxx.git HEAD:master
remote: You are not allowed to upload code.
fatal: unable to access 'https://gitlab-ci-token:[secure]@xxx.xxx.xxx/xxx/xxx/xxx.git/': The requested URL returned error: 403
    at makeError (/usr/local/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async verifyAuth (/usr/local/lib/node_modules/semantic-release/lib/git.js:207:5)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/lib/get-git-auth-url.js:91:5)
    at async run (/usr/local/lib/node_modules/semantic-release/index.js:56:27)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/cli.js:55:5)
2021-10-26T13:13:42.922Z semantic-release:get-git-auth-url SSH key auth failed, falling back to https.
2021-10-26T13:13:44.063Z semantic-release:get-tags found tags for branch master: [ { gitTag: '1.0.0', version: '1.0.0', channels: [ null ] }, { gitTag: '1.1.0', version: '1.1.0', channels: [ null ] }, { gitTag: '1.2.0', version: '1.2.0', channels: [ null ] }, { gitTag: '1.3.0', version: '1.3.0', channels: [ null ] }, { gitTag: '1.4.0', version: '1.4.0', channels: [ null ] }, { gitTag: '1.4.1', version: '1.4.1', channels: [ null ] }, { gitTag: '1.5.0', version: '1.5.0', channels: [ null ] }, { gitTag: '1.6.0', version: '1.6.0', channels: [ null ] }, { gitTag: '1.7.0', version: '1.7.0', channels: [ null ] }, { gitTag: '1.8.0', version: '1.8.0', channels: [ null ] } ]
[1:13:44 PM] [semantic-release] › ✔  Run automated release from branch master on repository https://gitlab-ci-token:[secure]@xxx.xxx.xxx/xxx/xxx/xxx.git
[1:13:44 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[1:13:44 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
2021-10-26T13:13:44.339Z semantic-release:gitlab apiUrl: 'http://xxx.xxx.xxx/api/v4'
2021-10-26T13:13:44.339Z semantic-release:gitlab repoId: 'xxx/xxx/xxx'
[1:13:44 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (http://xxx.xxx.xxx/api/v4)
[1:13:44 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/gitlab"
[1:13:44 PM] [semantic-release] › ✖  EMISSINGREPO The repository xxx/xxx/xxx doesn't exist.
The semantic-release repositoryUrl option must refer to your GitLab repository. The repository must be accessible with the GitLab API (https://docs.gitlab.com/ce/api/README.html).
By default the repositoryUrl option is retrieved from the repository property of your package.json or the git origin url (https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes) of the repository cloned by your CI environment.
If you are using GitLab Enterprise Edition (https://about.gitlab.com/gitlab-ee) please make sure to configure the gitlabUrl and gitlabApiPathPrefix options (https://github.com/semantic-release/gitlab/blob/master/README.md#options).
AggregateError:
    SemanticReleaseError: The repository xxx/xxx/xxx doesn't exist.
        at module.exports (/usr/local/lib/node_modules/@semantic-release/gitlab/lib/get-error.js:6:10)
        at module.exports (/usr/local/lib/node_modules/@semantic-release/gitlab/lib/verify.js:65:21)
    at /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/usr/local/lib/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/usr/local/lib/node_modules/semantic-release/index.js:95:3)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/cli.js:55:5)
Cleaning up file based variables 00:01
ERROR: Job failed: command terminated with exit code 1
```

**Comment by khan0amh** [comment]
In my case the logs just end here:
```
[3:28:08 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[3:28:08 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[3:28:09 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 3 file(s) to commit
```

And the pipeline cancelled itself.

**Comment by cpflugra** [comment]
Update: After updating our self hosted GitLab instance to 14.7.2 I removed the workaround and can't reproduce the bug anymore.

I'm closing this issue as the solution seems to be to update your GitLab instance to at least version 14.7.2.
