### ISSUE TITLE
TypeError: VALIDATORS[option] is not a function

### ISSUE THREAD

**Issue by hvanoch** [semantic-release/gitlab#363]
This popped up today. Was working fine last week.

My release.config.js looks like
```
        [
            "@semantic-release/gitlab",
            {
                successComment: false
            }
        ],
```
```
$ npx semantic-release
[8:55:36 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.2
[8:55:37 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[8:55:37 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-slack-bot"
[8:55:37 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[8:55:37 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[8:55:37 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[8:55:37 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/gitlab"
[8:55:37 AM] [semantic-release] › ✔  Loaded plugin "success" from "semantic-release-slack-bot"
[8:55:37 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/gitlab"
[8:55:37 AM] [semantic-release] › ✔  Loaded plugin "fail" from "semantic-release-slack-bot"
[8:55:37 AM] [semantic-release] › ✔  Run automated release from branch staging on repository https://gitlab-ci-token:[secure]@gitlab-ext.cu.be/henne/oms.git
[8:55:38 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[8:55:38 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[8:55:38 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/gitlab"
[8:55:38 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "semantic-release-slack-bot"
[8:55:38 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "semantic-release-slack-bot"
[8:55:38 AM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: VALIDATORS[option] is not a function
    at /builds/henne/oms/node_modules/@semantic-release/gitlab/lib/verify.js:37:[43](https://gitlab-ext.cu.be/henne/oms/-/jobs/67701#L43)
    at Array.reduce (<anonymous>)
    at module.exports (/builds/henne/oms/node_modules/@semantic-release/gitlab/lib/verify.js:35:[47](https://gitlab-ext.cu.be/henne/oms/-/jobs/67701#L47))
    at verifyConditions (/builds/henne/oms/node_modules/@semantic-release/gitlab/index.js:11:9)
    at validator (/builds/henne/oms/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at /builds/henne/oms/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (/builds/henne/oms/node_modules/p-reduce/index.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  pluginName: '@semantic-release/gitlab'
}
AggregateError: 
    TypeError: VALIDATORS[option] is not a function
        at /builds/henne/oms/node_modules/@semantic-release/gitlab/lib/verify.js:37:43
        at Array.reduce (<anonymous>)
        at module.exports (/builds/henne/oms/node_modules/@semantic-release/gitlab/lib/verify.js:35:47)
        at verifyConditions (/builds/henne/oms/node_modules/@semantic-release/gitlab/index.js:11:9)
        at validator (/builds/henne/oms/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
        at /builds/henne/oms/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
        at next (/builds/henne/oms/node_modules/p-reduce/index.js:17:9)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /builds/henne/oms/node_modules/semantic-release/lib/plugins/pipeline.js:[54](https://gitlab-ext.cu.be/henne/oms/-/jobs/67701#L54):11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/builds/henne/oms/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/builds/henne/oms/node_modules/semantic-release/index.js:103:3)
    at async module.exports (/builds/henne/oms/node_modules/semantic-release/index.js:268:22)
    at async module.exports (/builds/henne/oms/node_modules/semantic-release/cli.js:[55](https://gitlab-ext.cu.be/henne/oms/-/jobs/67701#L55):5)
```

**Comment by fgreinacher** [comment]
@JonasSchubert Looks related to https://github.com/semantic-release/gitlab/pull/349/files, could you have a look?

**Comment by JonasSchubert** [comment]
@fgreinacher will do so on the coming weekend.
Could be related to missing validator for successComment. I forgot that. And will check if anything else is missing.

**Comment by JonasSchubert** [comment]
If it is urgent maybe. I'm on vacation and unfortunately without prober computer. Saturday is the earliest I can work on it

**Comment by fgreinacher** [comment]
I’ll have a look tomorrow (before leaving for vacation 😀)

**Comment by JonasSchubert** [comment]
I think we can either check whether an validator exists [here](https://github.com/semantic-release/gitlab/blob/bea6b3cf7872c81d5dd935259c5dbd0f832eb41f/lib/verify.js#L37). E.g.:
```js
      !isNil(value) && (!VALIDATORS || !VALIDATORS[option](value)) 
```

Or (in my opinion better) we add the missing validators [here](https://github.com/semantic-release/gitlab/blob/bea6b3cf7872c81d5dd935259c5dbd0f832eb41f/lib/verify.js#L15). I think the missing validators are `milestones` and `successComment`. E.g.:
```js
const VALIDATORS = {
  assets: isArrayOf(
    asset => isStringOrStringArray(asset) || (isPlainObject(asset) && isStringOrStringArray(asset.path))
  ),
  milestones: isArrayOf(
    milestone => isStringOrStringArray(milestone)
  ),
  successComment: canBeDisabled(isNonEmptyString),
  failTitle: canBeDisabled(isNonEmptyString),
  failComment: canBeDisabled(isNonEmptyString),
  labels: isNonEmptyString,
  assignee: isNonEmptyString,
};
```

Or remove the generic validator check and do each validation separately.

PS: thanks @fgreinacher for looking into it and sorry for the trouble
