### ISSUE TITLE
Unable to connect to GitLab from behind proxy in  "verifyConditions" of plugin "@semantic-release/gitlab"

### ISSUE THREAD

**Issue by MullaCode** [semantic-release/gitlab#392]
Hello

I'm having issues in the  Verify GitLab authentication stage when running npx semantic-release

Build is running in a Docker container via Jenkins behind a proxy. 
The proxy is set both as Environment variables (HTTP_PROXY & HTTPS_PROXY) and in the file /etc/sysconfig/docker
I know that the proxy is working as I can download from Gitlab already and I can install NPM modules. This is the output from the job:

16:09:34  [3:09:34 PM] [semantic-release] › ℹ  Running semantic-release version 19.0.2
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/exec"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/gitlab"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/gitlab"
16:09:34  [3:09:34 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
16:09:36  [3:09:36 PM] [semantic-release] › ✔  Run automated release from branch develop on repository [https://gitlab-ci-token:[secure]@xxxxxgitlab.xxxxx.com/xxxxx/xxxxx.git](https://gitlab-ci-token:%5Bsecure%5D@xxxxxgitlab.xxxxx.com/mule-dev-team/muleapiv2.git)
16:09:36  [3:09:36 PM] [semantic-release] › ✔  Allowed to push to the Git repository
16:09:36  [3:09:36 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
16:09:36  [3:09:36 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://xxxxxgitlab.xxxxx.com/api/v4)
16:16:13  [3:16:10 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/gitlab"
16:16:13  [3:16:10 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
16:16:13  [3:16:10 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
16:16:13  [3:16:10 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
16:16:13  [3:16:10 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
16:16:13  [3:16:10 PM] [semantic-release] › ✖  An error occurred while running semantic-release: RequestError: connect ETIMEDOUT 10.109.41.212:443
16:16:13      at ClientRequest.<anonymous> (/home/jenkins/workspace/_xxxx/node_modules/got/dist/source/core/index.js:970:111)
16:16:13      at Object.onceWrapper (events.js:520:26)
16:16:13      at ClientRequest.emit (events.js:412:35)
16:16:13      at ClientRequest.origin.emit (/home/jenkins/workspace/xxxx/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
16:16:13      at TLSSocket.socketErrorListener (_http_client.js:475:9)
16:16:13      at TLSSocket.emit (events.js:400:28)
16:16:13      at emitErrorNT (internal/streams/destroy.js:106:8)
16:16:13      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
16:16:13      at processTicksAndRejections (internal/process/task_queues.js:82:21)
16:16:13      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
16:16:13    code: 'ETIMEDOUT',

I'm using the latest version of @semantic-release/gitlab
I get a 200 response when I run curl https://reflex-gitlab.hannover-re.com/api/v4/projects in the same job and I know the token is correct as I get an error when I pass a dummy token. 

Is there another configuration I'm missing ?

**Comment by MullaCode** [comment]
Setting the ENV variables for the proxy wasn't enough on the host or /etc/sysconfig/docker level. I had to set the env vars right before executing npx semantic-release in the docker container.
