### ISSUE TITLE
ERR_REQUIRE_ESM error with semantic-release-monorepo

### ISSUE THREAD

**Issue by karlomedallo** [semantic-release/gitlab#493]
Hi, I'm trying to set this up with semantic-release-monorepo and I'm getting this error:
```
[12:10:32 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /builds/repo/node_modules/.pnpm/@semantic-release+gitlab@10.1.4_semantic-release@20.1.0/node_modules/@semantic-release/gitlab/index.js from /builds/repo/node_modules/.pnpm/semantic-release-plugin-decorators@3.0.1_semantic-release@20.1.0/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.
Instead change the require of index.js in /builds/repo/node_modules/.pnpm/semantic-release-plugin-decorators@3.0.1_semantic-release@20.1.0/node_modules/semantic-release-plugin-decorators/src/wrapStep.js to a dynamic import() which is available in all CommonJS modules.
    at semantic-release-monorepo (/builds/repo/node_modules/.pnpm/semantic-release-plugin-decorators@3.0.1_semantic-release@20.1.0/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:49:24)
    at validator (file:///builds/repo/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///builds/repo/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (file:///builds/repo/node_modules/.pnpm/p-reduce@3.0.0/node_modules/p-reduce/index.js:16:10) {
  code: 'ERR_REQUIRE_ESM',
  pluginName: '[Function: semantic-release-monorepo]'
}
Error [ERR_REQUIRE_ESM]: require() of ES Module /builds/repo/node_modules/.pnpm/@semantic-release+gitlab@10.1.4_semantic-release@20.1.0/node_modules/@semantic-release/gitlab/index.js from /builds/repo/node_modules/.pnpm/semantic-release-plugin-decorators@3.0.1_semantic-release@20.1.0/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.
Instead change the require of index.js in /builds/repo/node_modules/.pnpm/semantic-release-plugin-decorators@3.0.1_semantic-release@20.1.0/node_modules/semantic-release-plugin-decorators/src/wrapStep.js to a dynamic import() which is available in all CommonJS modules.
    at semantic-release-monorepo (/builds/repo/node_modules/.pnpm/semantic-release-plugin-decorators@3.0.1_semantic-release@20.1.0/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:49:24)
    at validator (file:///builds/repo/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///builds/repo/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (file:///builds/repo/node_modules/.pnpm/p-reduce@3.0.0/node_modules/p-reduce/index.js:16:10) {
  code: 'ERR_REQUIRE_ESM',
  pluginName: '[Function: semantic-release-monorepo]'
}undefined
/builds/repo/src/libs/eslint-config:
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with exit code 1: node_modules/.bin/semantic-release
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by JonasSchubert** [comment]
@semantic-release/gitlab was recently changed to ESM only. It looks like the package you are using is not compatible. Maybe try v9 and check whether it works with the previous version.

**Comment by fgreinacher** [comment]
As mentioned above downstream packages need to be ESM since v10.

**Comment by jcapogna** [comment]
I can confirm that downgrade @semantic-release/gitlab to v9 fixes this issue.
