### ISSUE TITLE
Failed step "verifyConditions" with EINVALIDGLTOKEN and EGITNOPERMISSION error

### ISSUE THREAD

**Issue by gimyboya** [semantic-release/gitlab#63]
I have been trying to figure this out for quite sometime now and i have tried all possible ways that i can think of.

The build is always failing with the following logs
```
[8:38:37 AM] [semantic-release] › ℹ  Running semantic-release version 15.13.3
[8:38:37 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[8:38:37 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[8:38:37 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[8:38:37 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[8:38:37 AM] [semantic-release] › ✔  Run automated release from branch master
[8:38:38 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[8:38:38 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[8:38:38 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.com/mygroup/myrepo.git/api/v4)
[8:38:38 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/gitlab"
[8:38:38 AM] [semantic-release] › ✖  EINVALIDGLTOKEN Invalid GitLab token.
....
[8:38:38 AM] [semantic-release] › ✖  EGLNOPERMISSION The GitLab token doesn't allow to push on the repository mygroup/myrepo.
....
```

weather i set the variables in gitlab CI/CD settings or in the `.releaserc` or in the `gitlab.ci.yml` all of these didn't work i even tried to put `"verifyConditions": [],` in the `@semantic-release/gitlab` options in the `.releserc` file

I have referred to this issue #19 but couldn't get much and in my case it's simply a project under a group not under a subgroup

any ideas on how i can get this work?

**Comment by pvdlg** [comment]
> weather i set the variables in gitlab CI/CD settings or in the .releaserc or in the gitlab.ci.yml all of these didn't work

I think there is some confusion there because environment variables cannot be set in `.releaserc`.

You have the set the environment variable `GH_TOKEN` with the value of a token associated with a user that is allowed to push to your repo.

**Comment by gimyboya** [comment]
@pvdlg Sorry, yes I was referring to the `GL_URL` and `GL_PREFIX` in that case as recommended [here](https://github.com/semantic-release/gitlab/issues/19#issuecomment-398395759)

**Comment by gimyboya** [comment]
as for the `GL_TOKEN` i have tried in both the `gitlab-ci-yml` and in the CI/CD settings

**Comment by pvdlg** [comment]
Can you run semantic-release with `--debug` and provide the full logs?

**Comment by gimyboya** [comment]
sure thing

```
$ npx semantic-release --debug
[6:12:26 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.3
2019-01-15T18:12:26.802Z semantic-release:config load config from: /builds/mygroup/myrepo/.releaserc.json
2019-01-15T18:12:26.807Z semantic-release:config options values: { branch: 'master',
  repositoryUrl: 'https://gitlab.com/mygroup/myrepo',
  tagFormat: 'v${version}',
  plugins:
   [ '@semantic-release/commit-analyzer',
     '@semantic-release/release-notes-generator',
     [ '@semantic-release/gitlab', [Object] ] ],
  _: [],
  debug: true,
  '$0': 'node_modules/.bin/semantic-release' }
2019-01-15T18:12:27.103Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: { gitlabUrl: 'https://gitlab.com/mygroup/myrepo.git',
  assets: [ { path: 'dist', label: 'distribution' } ] }
[6:12:27 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
2019-01-15T18:12:27.105Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[6:12:27 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2019-01-15T18:12:27.116Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[6:12:27 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2019-01-15T18:12:27.117Z semantic-release:plugins options for @semantic-release/gitlab/publish: { gitlabUrl: 'https://gitlab.com/mygroup/myrepo.git',
  assets: [ { path: 'dist', label: 'distribution' } ] }
[6:12:27 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[6:12:27 PM] [semantic-release] › ✔  Run automated release from branch master
2019-01-15T18:12:28.570Z semantic-release:git Error: Command failed: git push --dry-run https://gitlab.com/mygroup/myrepo HEAD:master
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.com/mygroup/myrepo.git/'


    at makeError (/builds/mygroup/myrepo/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/builds/mygroup/myrepo/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[6:12:28 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[6:12:28 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
2019-01-15T18:12:28.798Z semantic-release:gitlab repoId: 'mygroup/myrepo'
2019-01-15T18:12:28.799Z semantic-release:gitlab apiUrl: 'https://gitlab.com/mygroup/myrepo.git/api/v4'
[6:12:28 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.com/mygroup/myrepo.git/api/v4)
[6:12:28 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/gitlab"
[6:12:28 PM] [semantic-release] › ✖  EINVALIDGLTOKEN Invalid GitLab token.
The GitLab token (https://github.com/semantic-release/gitlab/blob/master/README.md#gitlab-authentication) configured in the GL_TOKEN or GITLAB_TOKEN environment variable must be a valid personnal access token (https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html) allowing to push to the repository mygroup/myrepo.

Please make sure to set the GL_TOKEN or GITLAB_TOKEN environment variable in your CI with the exact value of the GitLab personnal token.

[6:12:28 PM] [semantic-release] › ✖  EGLNOPERMISSION The GitLab token doesn't allow to push on the repository mygroup/myrepo.
The user associated with the GitLab token (https://github.com/semantic-release/gitlab/blob/master/README.md#gitlab-authentication) configured in the GL_TOKEN or GITLAB_TOKEN environment variable must allows to push to the repository mygroup/myrepo.

Please make sure the GitLab user associated with the token has the permission to push (https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions) to the repository mygroup/myrepo.

{ AggregateError: 
    SemanticReleaseError: Invalid GitLab token.
        at module.exports (/builds/mygroup/myrepo/node_modules/@semantic-release/gitlab/lib/get-error.js:6:10)
        at module.exports (/builds/mygroup/myrepo/node_modules/@semantic-release/gitlab/lib/verify.js:58:21)
    SemanticReleaseError: The GitLab token doesn't allow to push on the repository mygroup/myrepo.
        at module.exports (/builds/mygroup/myrepo/node_modules/@semantic-release/gitlab/lib/get-error.js:6:10)
        at module.exports (/builds/mygroup/myrepo/node_modules/@semantic-release/gitlab/lib/verify.js:67:19)
    at /builds/mygroup/myrepo/node_modules/semantic-release/lib/plugins/pipeline.js:53:11
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }ERROR: Job failed: exit code 1
```

it seems that gitlab don't have push access while I have configured an access token that has push privileges and I am made an owner of the repo (not the group tho)

**Comment by gimyboya** [comment]
i am getting this on the console after doing the necessary replacements
```html
<html><body>You are being <a href="https://gitlab.com/users/sign_in">redirected</a>.</body></html>
```

**Comment by pvdlg** [comment]
That means GitLab redirects you to the sign in page, which confirmed what I said before: the token set in GH_TOKEN doesn't allow to access the GitLab API or that your configuration for the API url is wrong.

**Comment by gimyboya** [comment]
and how do i fix this exactly? because the token was generated from the settings page

**Comment by pvdlg** [comment]
What is the URL of your GitLab instance?
did you configured `GL_PREFIX` or `GL_URL`? To what value?

**Comment by gimyboya** [comment]
`GL_URL` `https://gitlab.com/grainer-core/rc-api.git`
`GL_Prefix` `/api/v4`

**Comment by gimyboya** [comment]
I can ommit the `GL_PREFIX` i set it just in case and it wasn't working with or without it also i thing in the debug file you can see the `repositoryUrl: 'https://gitlab.com/mygroup/myrepo'` the `repoId: 'mygroup/myrepo'` and the `apiUrl: 'https://gitlab.com/mygroup/myrepo.git/api/v4'` which for simplification i have replaced `grainer-core/rc-api` to `mygroup/myrepo`

**Comment by pvdlg** [comment]
Please see the documentation for `GL_URL`: https://github.com/semantic-release/gitlab#environment-variables

Is your GitLab instance URL is `https://gitlab.com/grainer-core/rc-api.git`? Because it looks like the URL of your repo, not the URL of GitLab.

**Comment by gimyboya** [comment]
kindly read the above reply :) I changed the debug output before pasting it to make things easier

**Comment by pvdlg** [comment]
I understood that you made this replacement in the logs. That doesn't change my point though.

`https://gitlab.com/grainer-core/rc-api.git` or `https://gitlab.com/mygroup/myrepo.git` or `https://gitlab.com/anything/anything.git` doesn't look like the URL of a GitLab instance. It look like the URL of a repo.

This is why I pointed you to the documentation explaining that `GL_URL` has to be set with the URL of you GitLab instance while it seems you put your repo URL in there.

**Comment by gimyboya** [comment]
@pvdlg Thank you very much the problem was indeed in the `GL_URL` as I understood it to be the repository url

**Comment by esciara** [comment]
> In order to verify the permission semantic-release will run the equivalent of `curl --header "X-Private-Token: ${GH_TOKEN}" https://gitlab.com/mygroup/myrepo.git/api/v4/projects/mygroup/myrepo`.

As a correction (as I spent quite some time understanding what was going wrong) the correct `curl` to use is:
```
curl --header "Private-Token: ${GH_TOKEN}" ${GH_URL}${GL_PREFIX}/projects/mygroup%2Fmyrepo
```
So `Private-Token` instead of `X-Private-Token` and `mygroup%2Fmyrepo` instead of `mygroup/myrepo`. See [GitLab's API doc on personal access tokens](https://docs.gitlab.com/ee/api/#personal-access-tokens) and [GitLab's API doc on namespaced path encoding](https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding).

In this particular case, the correct `curl` would be:
```
curl --header "Private-Token: <your_access_token>" https://gitlab.com/api/v4/projects/mygroup%2Fmyrepo
```

Since [by default](https://github.com/semantic-release/gitlab#options) the options `gitlabUrl = https://gitlab.com` and  `gitlabApiPathPrefix = /api/v4`, in your case, you would only need to setup `GH_TOKEN`.

As another note, if you still cannot access your project with this `curl`, try `curl --header "Private-Token: <your_access_token>" https://gitlab.com/api/v4/projects`. If this time you get a response, if you also are behind a reverse proxy, it might be that your reverse proxy is not correctly configured, and decodes the `%2F` into a `/`, hence forwarding a `https://gitlab.com/api/v4/projects/mygroup/myrepo`, which will result in a `{"error": "404 Not Found"}`.

See [this GitLab issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/35079) for more details, including a correction of reverse proxy configuration. Careful about the solution provided, it might not be a full proof secure solution of Nginx revers proxy, see [this Nginx ticket](https://trac.nginx.org/nginx/ticket/727) for more info and [this stackoverflow entry](https://stackoverflow.com/a/37584637) for a potentially more secure solution.
