### ISSUE TITLE
Failed step "verifyConditions" of plugin "@semantic-release/gitlab"

### ISSUE THREAD

**Issue by joelnet** [semantic-release/gitlab#64]
Can't get passed `"verifyConditions"` with the `@semantic-release/gitlab` plugin.

```
$ npx semantic-release --debug
npx: installed 782 in 21.926s
[9:14:04 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.3
2019-01-28T21:14:04.378Z semantic-release:config load config from: /builds/development/library/javascript/react-primitive-components/.releaserc.yml
2019-01-28T21:14:04.386Z semantic-release:config options values: { branch: 'master',
  repositoryUrl:
   'git@gitlabdev.paciolan.info:development/library/javascript/react-primitive-components.git',
  tagFormat: 'v${version}',
  plugins:
   [ '@semantic-release/commit-analyzer',
     '@semantic-release/release-notes-generator',
     [ '@semantic-release/gitlab', [Object] ] ],
  release: { branch: 'master' },
  _: [],
  debug: true,
  '$0': '/root/.npm/_npx/17/bin/semantic-release' }
2019-01-28T21:14:04.783Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: { gitlabUrl: 'https://gitlabdev.paciolan.info',
  verifyConditions: [],
  assets: [ { path: [Array], label: 'JS distribution' } ] }
[9:14:04 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
2019-01-28T21:14:04.786Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[9:14:04 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2019-01-28T21:14:04.786Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[9:14:04 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2019-01-28T21:14:04.787Z semantic-release:plugins options for @semantic-release/gitlab/publish: { gitlabUrl: 'https://gitlabdev.paciolan.info',
  verifyConditions: [],
  assets: [ { path: [Array], label: 'JS distribution' } ] }
[9:14:04 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[9:14:04 PM] [semantic-release] › ✔  Run automated release from branch master
[9:14:06 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:14:06 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
2019-01-28T21:14:06.700Z semantic-release:gitlab repoId: 'development/library/javascript/react-primitive-components'
2019-01-28T21:14:06.702Z semantic-release:gitlab apiUrl: 'https://gitlabdev.paciolan.info/api/v4'
[9:14:06 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlabdev.paciolan.info/api/v4)
[9:14:06 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/gitlab"
[9:14:06 PM] [semantic-release] › ✖  EGLNOPERMISSION The GitLab token doesn't allow to push on the repository development/library/javascript/react-primitive-components.
The user associated with the GitLab token (https://github.com/semantic-release/gitlab/blob/master/README.md#gitlab-authentication) configured in the GL_TOKEN or GITLAB_TOKEN environment variable must allows to push to the repository development/library/javascript/react-primitive-components.

Please make sure the GitLab user associated with the token has the permission to push (https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions) to the repository development/library/javascript/react-primitive-components.

{ AggregateError: 
    SemanticReleaseError: The GitLab token doesn't allow to push on the repository development/library/javascript/react-primitive-components.
        at module.exports (/builds/development/library/javascript/react-primitive-components/node_modules/@semantic-release/gitlab/lib/get-error.js:6:10)
        at module.exports (/builds/development/library/javascript/react-primitive-components/node_modules/@semantic-release/gitlab/lib/verify.js:67:19)
    at /root/.npm/_npx/17/lib/node_modules/semantic-release/lib/plugins/pipeline.js:53:11
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }ERROR: Job failed: exit code 1
```

`.releaserc.yml`:

```yaml
release:
  branch: master

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/gitlab"
    - gitlabUrl: https://gitlabdev.paciolan.info
      verifyConditions: [] # this seems to have no effect
      assets:
        - path:
            - dist
            - README.md
          label: JS distribution
```

`GITLAB_TOKEN` permissions:

Name | Created | Expires | Scopes |  
-- | -- | -- | -- | --
semantic-release | Jan 28, 2019 | In almost 80 years | api, read_user, read_repository | Revoke

I read through https://github.com/semantic-release/gitlab/issues/19, but wasn't able to get any workarounds working for me.

At the moment, I am stuck and need some guidance to be pointed in the right direction on this.

Cheers!

**Comment by pvdlg** [comment]
The user associated with the token need to have push permission on the repo. That's different than the  scope of the token.

**Comment by joelnet** [comment]
The user is set as a `Maintainer` and can push locally to the `master` branch.

This could be related to the gitlab group permissions bug.

**Comment by pvdlg** [comment]
What is the result of `curl --header "PRIVATE-TOKEN:<YOUR_TOKEN>"  https://gitlabdev.paciolan.info/projects/development/library/javascript/react-primitive-components` ?
In particular what's the value of the `permissions` property?

**Comment by joelnet** [comment]
Hmm... I'm getting a redirect message from the curl.

`<html><body>You are being <a href="https://gitlabdev.paciolan.info/users/sign_in">redirected</a>.</body></html>`

**Comment by pvdlg** [comment]
Sorry the correct curl command is `curl --header "PRIVATE-TOKEN:<YOUR_TOKEN>" https://gitlabdev.paciolan.info//api/v4/projects/development/library/javascript/react-primitive-components`

**Comment by pvdlg** [comment]
So as you can see from the error message `https://gitlabdev.paciolan.info/api/v4/projects/development/library/javascript/react-primitive-components` doesn't exists.

As [mentioned in the docs](https://github.com/semantic-release/gitlab#options) you have to set `gitlabUrl` and `gitlabApiPathPrefix` to match your environment.

**Comment by pvdlg** [comment]
semantic-release does support releasing with an ssh key: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/git-auth-ssh-keys.md

If you configure those variables as you mentioned that mean the plugin is going to call the GitLab API on `https://gitlabdev.paciolan.info/api/v4` however as the `curl` command showed you this URL doesn't exist. You have to configure those variable to your instance URL and to the prefix on whcih the API dis deployed.

If you API is accessible on `https://gitlabdev.paciolan.info/my-api` then you need to configure as follow:
```
gitlabUrl=https://gitlabdev.paciolan.info
gitlabApiPathPrefix=/my-api
```

**Comment by varijkapil13** [comment]
I am having the same problem. When I create the same url pattern as you mentioned in one of your comments above, I get `{"error": "404 not found"}` response. But then I try to find the url of the repository, by sending a request to `<gitlab_url>/api/v4/projects`, I get the same url as project url that I try to access before. 
BUT, in the links section, there is another url, that has project id in path, when I send a curl request to that url, I get a response back.

I don't know if this is something with this plugin or with gitlab, but this is making this plugin unusable... I think I also have to switch to semantic-release-gitlab, and see if that works....
