### ISSUE TITLE
409 Conflict error while posting release

### ISSUE THREAD

**Issue by gund** [semantic-release/gitlab#66]
Hi! I've been using this library for a long time with different providers (github, gitlab, bitbucket) and it was working always good.

However on one of my projects on gitlab I stated to face errors `409 Conflict` while posting a release for tags on master.

First I want to explain the model of releases that I'm using there to give you the context.

I have 2 main branches: master and develop.
Releases happen from both branches with different tag names:
- `v${version}` on master
- `v${version}-dev` on develop
This is done to simulate pre-peleases since this feature is still in beta.

Now everything on develop is working great. But when I merge to master release with tag is created but gitlab responds with `409 Conflict` and that fails the pipeline.

I think that there is something wrong with Gitlab API but before going to them I wanted to first ask here if it is not the problem of semantic release gitlab plugin by any chance.

<details><summary>Here is the log with `--debug` flag</summary>

```
[14:19:01] [semantic-release] › ℹ  Running semantic-release version 15.13.3
2019-02-04T14:19:01.530Z semantic-release:config load config from: /project/xxx/.releaserc
2019-02-04T14:19:01.556Z semantic-release:config options values: { branch: 'master',
  repositoryUrl: 'https://gitlab-ci-token:[secure]@xxx.com/project/xxx.git',
  tagFormat: 'v${version}',
  plugins: 
   [ '@semantic-release/commit-analyzer',
     '@semantic-release/release-notes-generator',
     [ '@semantic-release/changelog', [Object] ],
     [ '@semantic-release/npm', [Object] ],
     [ '@semantic-release/exec', [Object] ],
     [ '@semantic-release/git', [Object] ],
     [ '@semantic-release/gitlab', [Object] ] ],
  _: [],
  b: 'master',
  debug: true,
  '$0': 'node_modules/.bin/semantic-release' }
2019-02-04T14:19:06.014Z semantic-release:plugins options for @semantic-release/changelog/verifyConditions: { changelogFile: 'CHANGELOG.md',
  changelogTitle: '# Immoforce - Changelog' }
2019-02-04T14:19:06.016Z semantic-release:plugins options for @semantic-release/npm/verifyConditions: { npmPublish: false }
[14:19:06] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
2019-02-04T14:19:06.017Z semantic-release:plugins options for @semantic-release/exec/verifyConditions: { verifyReleaseCmd: './scripts/release-verify.sh "${nextRelease.gitTag}"',
  prepareCmd: './scripts/release-prepare.sh "${nextRelease.gitTag}"' }
[14:19:06] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[14:19:06] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
2019-02-04T14:19:06.018Z semantic-release:plugins options for @semantic-release/git/verifyConditions: { assets: [ 'CHANGELOG.md', 'package.json' ],
  message: 'chore(release): update version ${nextRelease.gitTag} [skip ci]' }
[14:19:06] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
2019-02-04T14:19:06.019Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: { gitlabUrl: 'https://xxx.com' }
[14:19:06] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
2019-02-04T14:19:06.020Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[14:19:06] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[14:19:06] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
2019-02-04T14:19:06.020Z semantic-release:plugins options for @semantic-release/exec/analyzeCommits: { verifyReleaseCmd: './scripts/release-verify.sh "${nextRelease.gitTag}"',
  prepareCmd: './scripts/release-prepare.sh "${nextRelease.gitTag}"' }
2019-02-04T14:19:06.021Z semantic-release:plugins options for @semantic-release/exec/verifyRelease: { verifyReleaseCmd: './scripts/release-verify.sh "${nextRelease.gitTag}"',
  prepareCmd: './scripts/release-prepare.sh "${nextRelease.gitTag}"' }
2019-02-04T14:19:06.021Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[14:19:06] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
[14:19:06] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[14:19:06] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
2019-02-04T14:19:06.022Z semantic-release:plugins options for @semantic-release/exec/generateNotes: { verifyReleaseCmd: './scripts/release-verify.sh "${nextRelease.gitTag}"',
  prepareCmd: './scripts/release-prepare.sh "${nextRelease.gitTag}"' }
[14:19:06] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
2019-02-04T14:19:06.022Z semantic-release:plugins options for @semantic-release/changelog/prepare: { changelogFile: 'CHANGELOG.md',
  changelogTitle: '# Immoforce - Changelog' }
[14:19:06] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
2019-02-04T14:19:06.023Z semantic-release:plugins options for @semantic-release/npm/prepare: { npmPublish: false }
2019-02-04T14:19:06.023Z semantic-release:plugins options for @semantic-release/exec/prepare: { verifyReleaseCmd: './scripts/release-verify.sh "${nextRelease.gitTag}"',
  prepareCmd: './scripts/release-prepare.sh "${nextRelease.gitTag}"' }
[14:19:06] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
2019-02-04T14:19:06.024Z semantic-release:plugins options for @semantic-release/git/prepare: { assets: [ 'CHANGELOG.md', 'package.json' ],
  message: 'chore(release): update version ${nextRelease.gitTag} [skip ci]' }
[14:19:06] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
2019-02-04T14:19:06.025Z semantic-release:plugins options for @semantic-release/npm/publish: { npmPublish: false }
[14:19:06] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
2019-02-04T14:19:06.025Z semantic-release:plugins options for @semantic-release/exec/publish: { verifyReleaseCmd: './scripts/release-verify.sh "${nextRelease.gitTag}"',
  prepareCmd: './scripts/release-prepare.sh "${nextRelease.gitTag}"' }
[14:19:06] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
2019-02-04T14:19:06.026Z semantic-release:plugins options for @semantic-release/gitlab/publish: { gitlabUrl: 'https://xxx.com' }
[14:19:06] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[14:19:06] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
2019-02-04T14:19:06.026Z semantic-release:plugins options for @semantic-release/exec/success: { verifyReleaseCmd: './scripts/release-verify.sh "${nextRelease.gitTag}"',
  prepareCmd: './scripts/release-prepare.sh "${nextRelease.gitTag}"' }
2019-02-04T14:19:06.027Z semantic-release:plugins options for @semantic-release/exec/fail: { verifyReleaseCmd: './scripts/release-verify.sh "${nextRelease.gitTag}"',
  prepareCmd: './scripts/release-prepare.sh "${nextRelease.gitTag}"' }
[14:19:06] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
[14:19:06] [semantic-release] › ✔  Run automated release from branch master
2019-02-04T14:19:06.993Z semantic-release:git Error: Command failed: git push --dry-run https://gitlab-ci-token:[secure]@xxx.com/project/xxx.git HEAD:master
remote: You are not allowed to upload code.
fatal: unable to access 'https://gitlab-ci-token:[secure]@xxx.com/project/xxx.git/': The requested URL returned error: 403


    at makeError (/project/xxx/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/project/xxx/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[14:19:07] [semantic-release] › ✔  Allowed to push to the Git repository
[14:19:07] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[14:19:07] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[14:19:07] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[14:19:07] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[14:19:07] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
[14:19:07] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
[14:19:07] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[14:19:07] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[14:19:07] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
2019-02-04T14:19:07.364Z semantic-release:gitlab repoId: 'project/xxx'
2019-02-04T14:19:07.365Z semantic-release:gitlab apiUrl: 'https://xxx.com/api/v4'
[14:19:07] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://xxx.com/api/v4)
[14:19:07] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
2019-02-04T14:19:08.116Z semantic-release:get-last-release found tags: []
[14:19:08] [semantic-release] › ℹ  No git tag version found
[14:19:08] [semantic-release] › ℹ  No previous release found, retrieving all commits
[14:19:08] [semantic-release] › ℹ  Found 5706 commits since last release
2019-02-04T14:19:08.626Z semantic-release:get-commits Parsed commits: [...]
[14:19:08] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[14:19:10] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci(gitlab): run release in debug mode
...
[14:19:10] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is major
2019-02-04T14:19:10.586Z semantic-release:commit-analyzer Analyzing with default rules
2019-02-04T14:19:10.586Z semantic-release:commit-analyzer The rule { breaking: true, release: 'major' } match commit with release type 'major'
2019-02-04T14:19:10.586Z semantic-release:commit-analyzer Release type 'major' is the highest possible. Stop analysis.
[14:19:10] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 5706 commits complete: major release
[14:19:10] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[14:19:10] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/exec"
[14:19:10] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/exec"
[14:19:10] [semantic-release] › ℹ  There is no previous release, the next release version is 1.0.0
[14:19:10] [semantic-release] › ℹ  Start step "verifyRelease" of plugin "@semantic-release/exec"
[14:19:10] [semantic-release] [@semantic-release/exec] › ℹ  Call script ./scripts/release-verify.sh "v1.0.0"
Running sonarqube testing on version v1.0.0 in publish mode!
[14:20:43] [semantic-release] › ✔  Completed step "verifyRelease" of plugin "@semantic-release/exec"
[14:20:43] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2019-02-04T14:20:45.370Z semantic-release:release-notes-generator version: '1.0.0'
2019-02-04T14:20:45.370Z semantic-release:release-notes-generator host: 'xxx.com'
2019-02-04T14:20:45.370Z semantic-release:release-notes-generator owner: 'angularjs'
2019-02-04T14:20:45.371Z semantic-release:release-notes-generator repository: 'project-xxx'
2019-02-04T14:20:45.371Z semantic-release:release-notes-generator previousTag: undefined
2019-02-04T14:20:45.371Z semantic-release:release-notes-generator currentTag: 'v1.0.0'
[14:20:46] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[14:20:46] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/exec"
[14:20:46] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/exec"
[14:20:46] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[14:20:46] [semantic-release] [@semantic-release/changelog] › ℹ  Update /project/xxx/CHANGELOG.md
[14:20:46] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[14:20:46] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[14:20:46] [semantic-release] [@semantic-release/npm] › ℹ  Write version 1.0.0 to package.json in /project/xxx
v1.0.0
[14:20:47] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[14:20:47] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/exec"
[14:20:47] [semantic-release] [@semantic-release/exec] › ℹ  Call script ./scripts/release-prepare.sh "v1.0.0"
Writing version `1.0.0` into file ./src/generated/version.ts
[14:20:47] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/exec"
[14:20:47] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
2019-02-04T14:20:47.925Z semantic-release:git globed assets: [ 'CHANGELOG.md', 'package.json' ]
[14:20:47] [semantic-release] [@semantic-release/git] › ℹ  Found 2 file(s) to commit
2019-02-04T14:20:48.003Z semantic-release:git add file to git index { stdout: '',
  stderr: '',
  code: 0,
  failed: false,
  killed: false,
  signal: null,
  cmd: 'git add --force --ignore-errors CHANGELOG.md package.json',
  timedOut: false }
2019-02-04T14:20:48.004Z semantic-release:git commited files: [ 'CHANGELOG.md', 'package.json' ]
[14:20:49] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: v1.0.0
[14:20:49] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
[14:20:49] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2019-02-04T14:20:51.387Z semantic-release:release-notes-generator version: '1.0.0'
2019-02-04T14:20:51.388Z semantic-release:release-notes-generator host: 'xxx.com'
2019-02-04T14:20:51.388Z semantic-release:release-notes-generator owner: 'angularjs'
2019-02-04T14:20:51.388Z semantic-release:release-notes-generator repository: 'project-xxx'
2019-02-04T14:20:51.388Z semantic-release:release-notes-generator previousTag: undefined
2019-02-04T14:20:51.388Z semantic-release:release-notes-generator currentTag: 'v1.0.0'
[14:20:52] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[14:20:52] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/exec"
[14:20:52] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/exec"
[14:20:53] [semantic-release] › ✔  Created tag v1.0.0
[14:20:53] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/npm"
[14:20:53] [semantic-release] [@semantic-release/npm] › ℹ  Skip publishing to npm registry as npmPublish is false
[14:20:53] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/npm"
[14:20:53] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/exec"
[14:20:53] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/exec"
[14:20:53] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/gitlab"
2019-02-04T14:20:53.948Z semantic-release:gitlab repoId: 'project/xxx'
2019-02-04T14:20:53.948Z semantic-release:gitlab release name: 'v1.0.0'
2019-02-04T14:20:53.948Z semantic-release:gitlab release ref: 'c121389491e42e02a3be4c38b3768120f1767ac6'
2019-02-04T14:20:53.948Z semantic-release:gitlab Update git tag 'v1.0.0' with commit 'c121389491e42e02a3be4c38b3768120f1767ac6' and release description
[14:20:54] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/gitlab"
[14:20:54] [semantic-release] › ✖  An error occurred while running semantic-release: { HTTPError: Response code 409 (Conflict)
    at EventEmitter.emitter.on (/project/xxx/node_modules/got/source/as-promise.js:74:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HTTPError',
  host: 'xxx.com',
  hostname: 'xxx.com',
  method: 'POST',
  path: '/api/v4/projects/project-xxx/repository/tags/v1.0.0/release',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://xxx.com/api/v4/projects/project-xxx/repository/tags/v1.0.0/release',
  gotOptions: 
   { path: '/api/v4/projects/project-xxx/repository/tags/v1.0.0/release',
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'xxx.com',
     port: null,
     hostname: 'xxx.com',
     hash: null,
     search: null,
     query: null,
     pathname: '/api/v4/projects/project-xxx/repository/tags/v1.0.0/release',
     href: 'https://xxx.com/api/v4/projects/project-xxx/repository/tags/v1.0.0/release',
     retry: 
      { retries: [Function],
        methods: [Object],
        statusCodes: [Object],
        errorCodes: [Object] },
     headers: 
      { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
        'private-token': '[secure]',
        accept: 'application/json',
        'accept-encoding': 'gzip, deflate',
        'content-type': 'application/json',
        'content-length': 121463 },
     hooks: 
      { beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [],
        beforeError: [],
        init: [] },
     decompress: true,
     throwHttpErrors: true,
     followRedirect: true,
     stream: false,
     form: false,
     json: true,
     cache: false,
     useElectronNet: false,
     body: "...",
     method: 'POST' },
  statusCode: 409,
  statusMessage: 'Conflict',
  headers: 
   { server: 'nginx',
     date: 'Mon, 04 Feb 2019 14:20:54 GMT',
     'content-type': 'application/json',
     'content-length': '36',
     connection: 'close',
     'cache-control': 'no-cache',
     vary: 'Origin',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'SAMEORIGIN',
     'x-request-id': '2c2fff65-dcd2-4bfa-9271-c5a438f7fd11',
     'x-runtime': '0.070336' },
  body: { message: 'Release already exists' },
  pluginName: '@semantic-release/gitlab' }

  ERROR: Job failed: command terminated with exit code 1
```

</details>

**Comment by pvdlg** [comment]
I don't know why it would return this error. The call seems conform wit the documentation: https://docs.gitlab.com/ee/api/tags.html#create-a-new-release.

According to your explanation it seems the API return a 409 when trying to add a release to a tag pointing to a commit that is already referenced by another tag. I don't see why it would be forbidden.
So it looks like a GitLab API bug to me.

**Comment by pvdlg** [comment]
Seems a bug on GitLab side. Please re-open if not.

**Comment by EvanCarroll** [comment]
I'm also getting this,

```text
[1:51:33 AM] [semantic-release] [@semantic-release/gitlab] › ✖  An error occurred while making a request to the GitLab release API:
HTTPError: Response code 409 (Conflict)
    at EventEmitter.<anonymous> (/builds/ec-ng-ui/angular-validators/node_modules/got/dist/source/as-promise.js:118:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1:51:33 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/gitlab"
[1:51:33 AM] [semantic-release] › ✖  An error occurred while running semantic-release: HTTPError: Response code 409 (Conflict)
    at EventEmitter.<anonymous> (/builds/ec-ng-ui/angular-validators/node_modules/got/dist/source/as-promise.js:118:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  pluginName: '@semantic-release/gitlab'
}
HTTPError: Response code 409 (Conflict)
    at EventEmitter.<anonymous> (/builds/ec-ng-ui/angular-validators/node_modules/got/dist/source/as-promise.js:118:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  pluginName: '@semantic-release/gitlab'
}
```

**Comment by EvanCarroll** [comment]
Ok. I now know the error here.

The problem is in the [gitlab setup docs it says](https://docs.gitlab.com/ee/ci/examples/semantic-release.html)

```yaml
default:
  image: node:latest
  before_script:
    - npm ci --cache .npm --prefer-offline
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee --append .npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
```


This is again mentioned in the [npmrc docs](https://docs.gitlab.com/ee/user/packages/npm_registry/#authenticate-to-the-package-registry)

```
@foo:registry=https://gitlab.example.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
//gitlab.example.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}
```

But this is **NOT** correct if your repository is in a GitLab Group different from the npm scope.

So for example, I wanted to publish the package `@acme/foo` to the repository `not-acme/foo`. To fix this I simply changed the above line to,

        echo "@acme:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
