### ISSUE TITLE
Gitlab user doesnt have access to push to the repo

### ISSUE THREAD

**Issue by vidur149** [semantic-release/gitlab#75]
Please help me solve this error message. I have created the Gitlab token, gave all the permissions to the token. I have access rights to push to the repo, which is a private project. I am still not able to use semantic-release. I guess I am doing something wrong but what exactly is the problem I am not able to find out. Below are the configs for my yml file and the semantic release logs.

```package.json```
``` 
"release": {
    "branch": "test",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      "@semantic-release/git",
      [
        "@semantic-release/gitlab",
        {
          "gitlabUrl": "https://gitlab*******.git"
        }
      ]
    ]
  }
```

gitlab.yml file

```
generate_changelog:
  stage: changelog
  script:
    - GL_TOKEN=$GL_TOKEN npx semantic-release --debug --no-ci
  only:
    - test
```

Semantic Release log
```
Running with gitlab-runner 11.11.2 (ac2a293c)
  on runner 7aae4c08
Using Docker executor with image node:11.15.0 ...
Pulling docker image node:11.15.0 ...
Using docker image sha256:58d70293b90018444a96aaa31ec0192b1e40f243effa266bdc231e55d879b777 for node:11.15.0 ...
Running on runner-7aae4c08-project-139-concurrent-0 via 7f334a473c6f...
Reinitialized existing Git repository in /builds/ma/ui_g2/.git/
Fetching changes...
Checking out 6192de7c as test...
Removing build/
Removing node_modules/

Skipping Git submodules setup
Checking cache for default...
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted. 
Successfully extracted cache
$ GL_TOKEN=$GL_TOKEN npx semantic-release --debug --no-ci
[6:06:32 AM] [semantic-release] › ℹ  Running semantic-release version 15.13.16
2019-06-11T06:06:32.748Z semantic-release:config load config from: /builds/ma/ui_g2/package.json
2019-06-11T06:06:32.753Z semantic-release:config options values: { branch: 'test',
  repositoryUrl: 'https://gitlab.orionic.com/ma/ui_g2',
  tagFormat: 'v${version}',
  plugins:
   [ '@semantic-release/commit-analyzer',
     '@semantic-release/release-notes-generator',
     '@semantic-release/changelog',
     '@semantic-release/git',
     [ '@semantic-release/gitlab', [Object] ] ],
  _: [],
  debug: true,
  ci: false,
  '$0': 'node_modules/.bin/semantic-release',
  noCi: true }
2019-06-11T06:06:33.004Z semantic-release:plugins options for @semantic-release/changelog/verifyConditions: {}
[6:06:33 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
2019-06-11T06:06:33.005Z semantic-release:plugins options for @semantic-release/git/verifyConditions: {}
[6:06:33 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
2019-06-11T06:06:33.005Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: { gitlabUrl: 'https://gitlab.orionic.com/ma/ui_g2.git' }
[6:06:33 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
2019-06-11T06:06:33.005Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[6:06:33 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2019-06-11T06:06:33.006Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[6:06:33 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2019-06-11T06:06:33.006Z semantic-release:plugins options for @semantic-release/changelog/prepare: {}
[6:06:33 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
2019-06-11T06:06:33.006Z semantic-release:plugins options for @semantic-release/git/prepare: {}
[6:06:33 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
2019-06-11T06:06:33.006Z semantic-release:plugins options for @semantic-release/gitlab/publish: { gitlabUrl: 'https://gitlab.orionic.com/ma/ui_g2.git' }
[6:06:33 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[6:06:33 AM] [semantic-release] › ✔  Run automated release from branch test
2019-06-11T06:06:33.215Z semantic-release:git Error: Command failed: git push --dry-run https://gitlab.orionic.com/ma/ui_g2 HEAD:test
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.orionic.com/ma/ui_g2.git/'


    at makeError (/builds/ma/ui_g2/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/builds/ma/ui_g2/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
[6:06:33 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[6:06:33 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[6:06:33 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[6:06:33 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[6:06:33 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[6:06:33 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
2019-06-11T06:06:33.355Z semantic-release:gitlab repoId: 'ma/ui_g2'
2019-06-11T06:06:33.355Z semantic-release:gitlab apiUrl: 'https://gitlab.orionic.com/ma/ui_g2.git/api/v4'
[6:06:33 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.orionic.com/ma/ui_g2.git/api/v4)
[6:06:33 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/gitlab"
[6:06:33 AM] [semantic-release] › ✖  EGLNOPERMISSION The GitLab token doesn't allow to push on the repository ma/ui_g2.
The user associated with the GitLab token (https://github.com/semantic-release/gitlab/blob/master/README.md#gitlab-authentication) configured in the GL_TOKEN or GITLAB_TOKEN environment variable must allows to push to the repository ma/ui_g2.

Please make sure the GitLab user associated with the token has the permission to push (https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions) to the repository ma/ui_g2.

[6:06:33 AM] [semantic-release] › ✖  EINVALIDGLTOKEN Invalid GitLab token.
The GitLab token (https://github.com/semantic-release/gitlab/blob/master/README.md#gitlab-authentication) configured in the GL_TOKEN or GITLAB_TOKEN environment variable must be a valid personnal access token (https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html) allowing to push to the repository ma/ui_g2.

Please make sure to set the GL_TOKEN or GITLAB_TOKEN environment variable in your CI with the exact value of the GitLab personnal token.

{ AggregateError: 
    SemanticReleaseError: Invalid GitLab token.
        at module.exports (/builds/ma/ui_g2/node_modules/@semantic-release/gitlab/lib/get-error.js:6:10)
        at module.exports (/builds/ma/ui_g2/node_modules/@semantic-release/gitlab/lib/verify.js:58:21)
    SemanticReleaseError: The GitLab token doesn't allow to push on the repository ma/ui_g2.
        at module.exports (/builds/ma/ui_g2/node_modules/@semantic-release/gitlab/lib/get-error.js:6:10)
        at module.exports (/builds/ma/ui_g2/node_modules/@semantic-release/gitlab/lib/verify.js:67:19)
    at /builds/ma/ui_g2/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (internal/process/task_queues.js:86:5) name: 'AggregateError' }ERROR: Job failed: exit code 1
```

**Comment by pvdlg** [comment]
Per the documentation `gitlabUrl` must be the GitLab server URL. It seems that you configured the full of your repo instead.

**Comment by vidur149** [comment]
@pvdlg where to find the gitlab URL according to me this is the `https://gitlab.orionic.com/ma/ui_g2.git` URL and this is what I have been using.

**Comment by pvdlg** [comment]
For the public GitLab the URL is `https://gitlab.com` and the repo URL look like `https://gitlab.com/user/repo.git`.
So I'm guessing in your case `https://gitlab.orionic.com`.

**Comment by vidur149** [comment]
@pvdlg Thanks, it worked. I feel so stupid doing this mistake. I had tried almost every permutation and combination and still wasnt able to find out.
